.pre-commit-config.yaml
poetry.lock
pyproject.toml

- Update gym-pusht version after having relaxed version requirements for `scikit-image` in `gym-pusht`: https://github.com/huggingface/gym-pusht/pull/9
- `poetry lock` (with updates)
-  `pre-commit autoupdate`
Only testing with the regular test suite

Relax version contraints & poetry lock

---

lerobot/common/policies/diffusion/modeling_diffusion.py

The input shape for SpatialSoftmax should be the crop shape, not the policy's input shape. This was working before by a lucky coincidence (downsampling ended up producing a feature map that was the same size for the cropped vs non-cropped version, but this wouldn't work for larger input images).

Fix SpatialSoftmax input shape

---

lerobot/common/policies/diffusion/configuration_diffusion.py
lerobot/common/policies/diffusion/modeling_diffusion.py
lerobot/configs/policy/diffusion.yaml

This PR adds DDIMScheduler as a choice for Diffusion Policy. DDPM can be too slow for real-world rollouts (takes ~0.7s on a 3080 with 100 timesteps, n_obs=2 and 216x288 images). This aims to get closer to real-time control (as is also mentioned in the DP paper).
I ran the standard test suite + diffusion-pushT training for some steps (screenshot attached).
I have not done a full training run and do not have performance numbers for this.
Add/update the `noise_scheduler_type` field in your diffusion config yaml.
```yaml
noise_scheduler_type: DDIM
num_train_timesteps: 100
num_inference_timesteps: 10 # optional but recommended
```

Support for DDIMScheduler in Diffusion Policy

---

lerobot/common/policies/tdmpc/configuration_tdmpc.py

comment fix
paramters -> parameters
Examples:

refactor: update configuration_tdmpc.py

---

.github/workflows/test.yml
tests/test_examples.py
tests/utils.py

Fixes #173
I've added a `pytest-minimal` job in CI to check that tests are passing with no envs installed: [successful job](https://github.com/huggingface/lerobot/actions/runs/9038285976/job/24839090214?pr=174)
Checkout this branch and run
```bash
poetry install --sync --extras "test"
DATA_DIR="tests/data" python -m pytest -v ./tests
```

Fix #173 - Require gym-pusht to be installed for test_examples_3_and_2

---

lerobot/common/logger.py

Quick fix for #152. 
Unnecessary if the string name for the datasets change. More discussion here: f80902b 
Ran training with a dataset with `/` in the string. Confirmed not to error. 
Run all tests except `test_examples_3_and_2`. Passed.
Run training with a dataset with `/` in the string. E.g.:
```
python lerobot/scripts/train.py     policy=act     env=aloha     env.task=AlohaInsertion-v0     dataset_repo_id=lerobot/aloha_sim_insertion_human
```

Fixes issue #152 - error with creating wandb artifact

---

examples/4_calculate_validation_loss.py
lerobot/common/datasets/utils.py
tests/test_examples.py

- I merged https://github.com/huggingface/lerobot/pull/158 but for some reason, the unit tests didnt pass.
- This PR includes hot fix to enable dynamic splitting from hugging face API even tho we load from disk using `DATA_DIR=tests/data`
```python
val_dataset = LeRobotDataset("lerobot/pusht", split="train[30:]")
```
Previously this was working:
```bash
python examples/4_calculate_validation_loss.py
```
But this wasn't:
```bash
DATA_DIR=tests/data python examples/4_calculate_validation_loss.py
```
Because the following was not supported when split != "train" (but "train[30:]")
```python
hf_dataset = load_from_disk(str(Path(root) / repo_id / split))
```
- This PR adds support for this via a hacky regexp matching. TODO: I will clean that in future PR by using logic from hugging face …

Hot fix to compute validation loss example test

---

lerobot/common/policies/diffusion/modeling_diffusion.py

This is a tiny change but might save someone a lot of hassle.
In the original implementation, we were saying: "oh cool, you want to mask the loss (that is what you set in the config) but well, if you didn't provide the `action_is_pad` in the batch, guess we will just ignore what you really wanted and just do something else".
I believe that the `config` should always take primacy and the user should not be ever saved like this, it is much better to throw an error
If we ignore the config this might lead to subtle bugs where the user expects some behavior, but gets something else, and troubleshooting this can be quite hard.
In fact, I would probably prefer this version even with the `ValueError` raised explicitly as it will be the same effect and as slightly more concise
``` 
if …
```

throw an error if config.do_maks_loss and action_is_pad not provided in batch

---

.github/workflows/build-docker-images.yml

Test artifacts were not `git lfs` pulled when building docker images and instead only the reference files were present — which obviously fails when trying to read them. This adds git lfs when checking out code to fix it.
Manually built & tested images on this branch successfully
- [Build run](https://github.com/huggingface/lerobot/actions/runs/9265632432)
- [Test run](https://github.com/huggingface/lerobot/actions/runs/9265859867)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/huggingface/lerobot/216)

Fix nightly builds

---

.github/workflows/nightly-tests.yml
Makefile

Enables `device=cuda` for end-to-end tests on gpu
Did a build & [nightly](https://github.com/huggingface/lerobot/actions/runs/9292950131/job/25575001007) run on this branch, with end-to-end tests successfully using `device=cuda` (while cpu remains unchanged)
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/huggingface/lerobot/222)

Enable cuda for end-to-end tests

---

lerobot/common/datasets/compute_stats.py
lerobot/common/datasets/factory.py
lerobot/common/datasets/lerobot_dataset.py
lerobot/common/datasets/utils.py
lerobot/configs/default.yaml
lerobot/scripts/push_dataset_to_hub.py
lerobot/scripts/train.py
tests/scripts/save_dataset_to_safetensors.py
tests/test_datasets.py

Adds `MultiLeRobotDataset` which essentially acts as a concatenation of multiple underlying `LeRobotDataset`s.
I am able to run training without an exception.
CI.
Run ACT/ALOHA training with `dataset_repo_id=["lerobot/aloha_static_battery","lerobot/aloha_static_coffee"]`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/huggingface/lerobot/229)

Add `MultiLerobotDataset` for training with multiple `LeRobotDataset`s

---

lerobot/common/datasets/lerobot_dataset.py
tests/test_datasets.py

Adds a missing `continue` in loop logic.
Adapted CI so that it would have caught the bug in the first place.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/huggingface/lerobot/233)

Fix chaining in MultiLerobotDataset

---

lerobot/common/utils/utils.py

Just a tiny addition to make the `format_big_number` more flexible.
Doesn't change default behavior but allows the caller to specify the precision of the returned value. Quite handy, as for millions or especially billion of params we might want to have that additional digit or two after the decimal point.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/huggingface/lerobot/232)

Add precision param to format_big_number

---

lerobot/common/datasets/sampler.py
lerobot/configs/policy/diffusion.yaml
lerobot/scripts/train.py
tests/test_sampler.py

EpisodeAwareSampler allows the dropping of first n or last n frames from each episode.
Additionally, you can select which episodes to run on by passig in their ids (complements functionality of the hf dataset slice syntax to give extra flexibility to the user).
* modify train.py and diffusion.yaml to leverage new functionality and train on pusht with last 7 steps per episode dropped
* add unit tests
resolves #129
I ran the train script for diffusion and act. Also, I ran tests locally -- got some failures but I believe they are not related. Ran the unit tests I wrote.
Best to create a toy dataset and verify that `sampler.indices` reflect params passed to the constructor (like done in unit tests)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

add EpisodeAwareSampler

---

examples/4_train_policy_with_script.md

Typo in examples\4_train_policy_with_script.md - aloha.yaml instead of pusht.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/huggingface/lerobot/235)

Typo in examples\4_train_policy_with_script.md

---

lerobot/common/policies/diffusion/modeling_diffusion.py

Removes `actions = sample[..., : self.config.output_shapes["action"][0]]` because given the logic in `conditional_sample` we are already guaranteed that `sample.shape[-1] == self.config.output_shapes["action"][0]`, and also because we end up making a smaller slice on the same dimension immediately after.
This was an artifact of the original DP code which has the same redundancy. Here, we remove it to avoid confusion (someone asked!)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/huggingface/lerobot/240)

Remove redundant slicing operation in Diffusion Policy

---

lerobot/scripts/visualize_dataset.py

Fixes
```bash
python lerobot/scripts/visualize_dataset.py --help
```
which returned
```bash
AttributeError: 'tuple' object has no attribute 'strip'
```
N/A
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/huggingface/lerobot/241)

Fix `visualize_dataset.py --help`

---

lerobot/common/policies/normalize.py

Fixes #211. Normalize class could have a divide by 0 problem, e.g. when some of the states or actions have a fixed value. 
Tested after extending push T / Diffusion policy to a real robot and fixing the non-XY states / actions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/huggingface/lerobot/239)

Fix bug in normalize to avoid divide by zero

---

lerobot/scripts/eval.py
lerobot/scripts/train.py
lerobot/scripts/visualize_dataset.py

Adds the ability to specify a custom output directory for the `eval.py` script.
Side changes:
- Change `def eval` to `def main` to avoid clash with native python `eval` (because it's good practice and makes it easier to read the code)
- Change the video directory to be called "video" instead of "eval" (more precise. I actually got confused for a moment and though I implemented the output directory incorrectly)
CI
To check that the custom output directory works:
`python lerobot/scripts/eval.py -p lerobot/diffusion_pusht --out-dir example_eval eval.n_episodes=1 eval.batch_size=1 +policy.noise_scheduler_type=DDIM policy.num_inference_steps=10`
To check that the default works:
`python lerobot/scripts/eval.py -p lerobot/diffusion_pusht eval.n_episodes=1 eval.batch_size=1 …

Add out_dir option to eval

---

lerobot/scripts/display_sys_info.py

Make `display_sys_info.py` install-agnostic so that any user can run it without having installed lerobot (usefull if one have issues installing the library and needs help).
Ran it successfully on a fresh conda env with nothing but python installed.
```bash
python lerobot/scripts/display_sys_info.py
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/huggingface/lerobot/253)

Make `display_sys_info.py` install-agnostic

---

lerobot/scripts/visualize_dataset.py
tests/test_visualize_dataset.py

This PR adds the `root` argument to the dataset visualizer. This parameter is passed to `LeRobotDataset.__init__`,  which enables visualizing local datasets, as an alternative to setting the `DATA_DIR` env variable.
closes #248 
- added a unit test to `tests/test_visualize_dataset` that visualizes the local copy of the `lerobot/pusht` dataset 
Examples:
```
python lerobot/scripts/visualize_dataset.py --repo-id lerobot/pusht --root tests/data/ --episode-index 0 --mode distant
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/huggingface/lerobot/249)

add root argument to the dataset visualizer to visualize local datasets

---

examples/4_train_policy_with_script.md

overriden -> overridden
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/huggingface/lerobot/257)

chore: update 4_train_policy_with_script.md

---

.github/workflows/test.yml
Makefile
lerobot/common/datasets/factory.py

- Fixes a mismatch between the format of the transforms parameter in `factory.py` when calling `get_image_transforms` and the configuration structure.
- Add `training.image_transforms.enable=true` in end-to-end tests as this issue passed CI unnoticed.
Newly modified CI end-to-end train test [failed](https://github.com/huggingface/lerobot/actions/runs/9483797227/job/26131760645) before modification. Test does [pass](https://github.com/huggingface/lerobot/actions/runs/9484987861/job/26135849139) after the fix.
You can run the test yourself, or run 
```bash
python lerobot/scripts/train.py device=cuda \
env=aloha \
env.task=AlohaTransferCube-v0 \
dataset_repo_id=lerobot/aloha_sim_transfer_cube_human \
policy=act \
training.offline_steps=1000 \
training.image_transforms.enable=true
```
- - - …

FIx make_dataset to match transforms config

---

lerobot/common/policies/diffusion/modeling_diffusion.py

This PR fixes global_cond_dim of Diffusion's unet when dim of observation.state != dim of action
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/huggingface/lerobot/278)

fix Unet global_cond_dim to use state dim, not action dim

---

lerobot/scripts/train.py
tests/test_policies.py

This pull request fix a bug where we were not identifying the backbone in the filtering of the parameters when specifying the learning rate for the backbone and for the main model.
As a result we were always assigning the main model LR for the back bone instead of the backbone specific LR, `lr_backbone`.
- Added `./tests/test_policies.py::test_act_backbone_lr`.
It can be tested with `pytest ./tests/test_policies.py::test_act_backbone_lr`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/huggingface/lerobot/280)

Bug fix: fix setting different learning rates between backbone and main model in ACT policy

---

README.md

This Pull Request detail how the LeRobot Dataset format is structured and created.
It also adds a mention of the often overlooked `DATA_DIR` environment variable.
It's extracted from https://github.com/huggingface/lerobot/pull/246
It's only a readme update thus no tests.
Read the changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/huggingface/lerobot/275)

Update readme to detail the lerobot dataset format

---

lerobot/configs/default.yaml
lerobot/scripts/train.py

^
I ran training with 10 offline steps (and save_freq > 10) and verified that the checkpoint was saved.
```bash
JOB_NAME=test
python lerobot/scripts/train.py \
hydra.job.name=$JOB_NAME \
hydra.run.dir=outputs/train/$(date +'%Y-%m-%d/%H-%M-%S')_${JOB_NAME} \
env=pusht \
policy=diffusion \
training.save_checkpoint=true \
training.offline_steps=10 \
training.save_freq=20000 \
training.eval_freq=10000 \
training.log_freq=50 \
eval.n_episodes=50 \
eval.batch_size=50 \
wandb.enable=false \
wandb.disable_artifact=true \
device=cuda \
use_amp=true
```

Checkpoint on final step of training even when it doesn't coincide with `save_freq`.

---

lerobot/configs/default.yaml
lerobot/configs/policy/act.yaml
lerobot/configs/policy/act_real.yaml
lerobot/configs/policy/act_real_no_state.yaml
lerobot/configs/policy/diffusion.yaml
lerobot/configs/policy/tdmpc.yaml
lerobot/configs/policy/vqbet.yaml

This addresses some inconsistencies found in the current config defaults. It also simplifies configs wherever possible.
For example, on `act.yaml`:
```diff
training:
online_steps: 0
- offline_steps: 80000
- save_freq: 100000
+ offline_steps: 100000
+ save_freq: 20000
```
N/A
N/A

Cleanup config defaults

---

lerobot/scripts/push_dataset_to_hub.py
tests/test_push_dataset_to_hub.py

`push_dataset_to_hub` with the `--tests-data-dir` option was not correctly updating `episode_data_index` to include _only_ the first episode. This PR fixes that and adds a test that would have caught it.
Side change: enables some tests that were skipped due to `required_package_arg` and the package not being specified properly `gym-pusht` -> `gym_pusht`

Fix generation of dataset test artifact

---

.pre-commit-config.yaml

While we already do have a [Trufflehog workflow](https://github.com/huggingface/lerobot/blob/main/.github/workflows/trufflehog.yml) in CI to check that we don't add secrets to the codebase, this is far from ideal as potential secrets are already committed & pushed when the CI runs.
This adds a [gitleaks](https://github.com/gitleaks/gitleaks) pre-commit which will check that no secret is added to the codebase _before_ they're even committed.
Other changes:
- `pre-commit autoupdate`
Staged this file:
```python
some_data = {
"ThisMightBeAKey": "AKIAIOSFODNN7EXAMPLE"
}
```
Ran the pre-commit:
```bash
Detect hardcoded secrets.................................................Failed
- hook id: gitleaks
- exit code: 1
○
│╲
│ ○
○ ░
░    gitleaks
Finding:     "ThisMightBeAKey": "REDACTED
Secret: …
```

Detect secrets in pre-commit

---

.github/workflows/build-docker-images.yml

Fix Docker builds in CI
Due to changing the runners in #351, git lfs is not installed on `aws-general-8-plus` runners. This fixes that by installing git lfs before checking out the repo.
Successfully built the images on this branch ([run](https://github.com/huggingface/lerobot/actions/runs/10354990797)).
N/A

Fix CI builds

---

examples/2_evaluate_pretrained_policy.py

Fixes an obvious bug in example 2 that somehow slipped by CI

fix bug in example 2

---

examples/7_get_started_with_real_robot.md

It simply fixes a typo error in 7_get_started_with_real_robot.md: '**repositery**' => '**repository**'
No tests were done.
https://github.com/ellacroix/lerobot/blob/2024_08_21_fix_typos_tutorial/examples/7_get_started_with_real_robot.md

Fix typo in tutorial

---

lerobot/common/utils/utils.py
lerobot/scripts/eval.py
lerobot/scripts/train.py
tests/test_utils.py

a2592a5563d20fecf0a8239e4af848d2bccbe4cd makes `init_hydra_config` less general because it now expects certain keys to be in the config. This PR removes that generality and moves the `env.batch_size` validation to the `train.py` and `eval.py` scripts.
Added CI to make sure the bug would have been caught.
Try `python lerobot/scripts/train.py eval.batch_size=10 eval.n_episodes=1` or `python lerobot/scripts/eval.py -p lerobot/diffusion_pusht_keypoints eval.batch_size=10 eval.n_episodes=1` to verify that the `env.batch_size` validation error is still raised.

Make sure `init_hydra_config` does not require any keys

---

lerobot/common/robot_devices/robots/koch.py
lerobot/configs/robot/koch.yaml

Moves `GRIPPER_OPEN_DEGREE` to `gripper_open_degree` in `KochRobotConfig`. This makes it possible to:
1. Not torque the leader arm's gripper if you want.
2. Set the gripper to be shut by default for tasks where gripping is not needed (eg pushing a block).
3. Set the gripper open to wider/narrower default actions to tailor to the task you want to do.
I ran this script:
```python
import tqdm
from lerobot.common.robot_devices.robots.factory import make_robot
from lerobot.common.robot_devices.robots.koch import KochRobot
from lerobot.common.utils.utils import init_hydra_config
robot_cfg = init_hydra_config("lerobot/configs/robot/koch_.yaml")
robot: KochRobot = make_robot(robot_cfg)
robot.connect()
seconds = 3000
frequency = 200
for _ in tqdm.tqdm(range(seconds*frequency)):
robot.teleop_step() …
```

Make gripper_open_degree a config param

---

lerobot/configs/robot/koch_bimanual.yaml

Title
Folded some shirts: https://x.com/RemiCadene/status/1828006677528137977
Visualized the dataset
https://huggingface.co/spaces/cadene/visualize_dataset_koch_bimanual_folding
```bash
python lerobot/scripts/control_robot.py teleoperate \
--robot-path lerobot/configs/robot/koch_bimanual.yaml 
python lerobot/scripts/train.py \
dataset_repo_id=cadene/koch_bimanual_folding \
policy=act_koch_real \
env=koch_real \
hydra.run.dir=outputs/train/act_koch_bimanual_folding \
hydra.job.name=act_koch_bimanual_folding \
device=cuda \
wandb.enable=true \
env.state_dim=12 \
env.action_dim=12 \
training.num_workers=8 \
training.batch_size=32 \
policy.n_decoder_layers=4
huggingface-cli upload cadene/act_koch_bimanual_folding \
outputs/train/act_koch_bimanual_folding/checkpoints/last/pretrained_model …
```

Add koch bimanual

---

lerobot/scripts/visualize_dataset_html.py
lerobot/templates/visualize_dataset_template.html

Adds a line under the video visualization in `visualize_dataset_html.py` to print the language instuction if it exists in the dataset.
Example from the `nyu_franka_play_dataset`:
I tested it by running `python lerobot/scripts/visualize_dataset_html.py` with several datasets from OpenX  and other datasets that don't contain language instruction like pusht.
To test it yourself:
NYU Franka play dataset
```
python lerobot/scripts/visualize_dataset_html.py --repo-id lerobot/nyu_franka_play_dataset --episodes 0
```
CMU Stretch dataset
```
python lerobot/scripts/visualize_dataset_html.py --repo-id lerobot/cmu_stretch --episodes 0 1 2 3
```
Imperial College Sawyer dataset
```
python lerobot/scripts/visualize_dataset_html.py --repo-id lerobot/imperialcollege_sawyer_wrist_cam --episodes 0 1 2 3
``` …

Add the possibility to visualize language instructions in visualize_dataset_html.py

---

lerobot/common/robot_devices/robots/koch.py

Fixes `KochRobot.send_action` when `max_relative_target` is not set (`None`)
@alexander-soare tested this logic on his robot in #396 (duplicate)
N/A

Fix safe_action

---

CONTRIBUTING.md

Replaced link opens a 404. This PR resolves that using `mailto` URI.
Tested on forked repo by PR author.
Please consider: `https://github.com/kghamilton89/lerobot/blob/fix-mailto/CONTRIBUTING.md`

repair mailto link

---

lerobot/common/policies/act/modeling_act.py

`n_vae_encoder_layers` configuration parameter was not being used In `lerobot/common/policies/act/modeling_act.py`. This PR updates the `ACTEncoder` class used for both the VAE and Transformer encoder to take a boolean argument `is_vae_encoder` and use `n_vae_encoder_layers` if true, else it will use `n_encoder_layers`.
- Trained an ACT model for 1000 steps after making the change and with `n_vae_encoder_layers=8` . Instructions to reproduce below
Conditional checkpoint to inspect number of layers created for VAE ACTEncoder 
Conditional checkpoint to in
spect number of layers created for Transformer ACTEncoder
- Currently running the pytest test suite...
- `pip install -e .[koch, test]`
- Update `lerobot/configs/policy/act_koch_real.yaml` to
```
#
seed: 1000
dataset_repo_id: …
```

fix(act): n_vae_encoder_layers config parameter wasn't being used

---

lerobot/configs/policy/tdmpc.yaml

Add missing `save_freq` key to `lerobot/configs/policy/tdmpc.yaml`
Without `save_freq` set I get the following error
```
Exception has occurred: MissingMandatoryValue
Missing mandatory value: training.save_freq
full_key: training.save_freq
object_type=dict
omegaconf.errors.MissingMandatoryValue: Missing mandatory value: $FULL_KEY
The above exception was the direct cause of the following exception:
File "/home/jack/code/rl/lerobot/lerobot/scripts/train.py", line 380, in evaluate_and_checkpoint_if_needed
step % cfg.training.save_freq == 0
File "/home/jack/code/rl/lerobot/lerobot/scripts/train.py", line 447, in train
evaluate_and_checkpoint_if_needed(step + 1, is_online=False)
File "/home/jack/code/rl/lerobot/lerobot/scripts/train.py", line 652, in train_cli
train(
File …
```

fix(tdmpc): Add missing save_freq to tdmpc policy config

---

lerobot/common/robot_devices/cameras/intelrealsense.py
lerobot/common/robot_devices/cameras/opencv.py
lerobot/configs/robot/aloha.yaml
poetry.lock
pyproject.toml

- Add intelrealsense.py in camera devices
- Use IntelRealSenseCamera as default for aloha.yaml robot config
- Can return depth map (with read and async_read)
TODO in https://github.com/huggingface/lerobot/pull/398:
- Found the camera indices using intelrealsense.py and looking at images.
- Used the camera indices in aloha.yaml
- Ran data recording.
- Checked the image from cameras are well displayed during data recording.
- Checked the bgr color mode works.
- Checked `read` and `async_read` returns proper color_image and depth_map.
- Checked `del camera` works
```python
camera.read()
(array([[[0, 0, 2],
[0, 0, 2],
[1, 1, 3],
...,
[0, 1, ..., 2, 1],
[0, 2, 1]]], dtype=uint8), array([[0, 0, 0, ..., 0, 0, 0],
[0, 0, 0, ..., 0, 0, 0],
[0, 0, 0, ...,...   [0, 0, 0, ..., 0, 0, 0]], …
```

Add IntelRealSenseCamera

---

lerobot/scripts/control_robot.py

Fixes calibrate arms option type. should be str not int.
Was getting the following error when pass `--arms` option to calibrate
```
(venv) jack@jackml:~/code/rl/lerobot (jv/fix-control-robot-ams-type)$ python lerobot/scripts/control_robot.py calibrate --robot-path lerobot/configs/robot/koch_jack.yaml --robot-overrides '~cameras' --arms main_follower main_leader
usage: control_robot.py calibrate [-h] [--robot-path ROBOT_PATH] [--robot-overrides [ROBOT_OVERRIDES ...]]
[--arms [ARMS ...]]
control_robot.py calibrate: error: argument --arms: invalid int value: 'main_follower'
```
Ran calibrate and confirmed I was no longer getting the error and that calibration succeeded. Further confirmed that teleoperation was working as expected after calibration.
Here's the calibrate output after fixing …

fix(calibrate): fix calibrate arms option type. should be str not int

---

lerobot/templates/visualize_dataset_template.html

`lerobot/scripts/visualize_dataset_html.py` had assumption that `dim state == dim action`. But this assumption could be broken at times. Therefore, this PR fixes `lerobot/scripts/visualize_dataset_html.py` when `dim state != dim action`.
```
python lerobot/scripts/visualize_dataset_html.py --repo-id lerobot/iamlab_cmu_pickup_insert --episodes 0
```

[Visualization tool] Fix when dim state != dim action

---

lerobot/templates/visualize_dataset_template.html

Show user feedback saying that "videos can not play" if the browser does not support lerobot video codec. Otherwise, it is confusing for the user not to show any error but yet not play the videos.

[Vizualization] Show user error if videos codec is not supported

---

lerobot/common/policies/diffusion/configuration_diffusion.py

Does this
```python
downsampling_factor = 2 ** len(self.down_dims)
if self.horizon % downsampling_factor != 0:
raise ValueError(
"The horizon should be an integer multiple of the downsampling factor (which is determined "
f"by `len(down_dims)`). Got {self.horizon=} and {self.down_dims=}"
)
```
Without this input validation we end up getting an obscure error during the forward pass:
`RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 10 but got size 9 for tensor number 1 in the list.`
No CI added. I just tried running training with various values of `horizon` and checked that that the `ValueError` is raised where the `RuntimeError` would have otherwise been raised.
This should raise the error.
`python lerobot/scripts/train.py policy=diffusion policy.horizon=18` …

Raise ValueError if horizon is incompatible with downsampling

---

lerobot/templates/visualize_dataset_template.html

Fixes a bug noticed by @aliberts. The bug is: some videos were getting clipped when video sizes were different.
This PR fixes the issue

[Vizualization] Fix video layout

---

lerobot/templates/visualize_dataset_template.html

Better error message written by @Cadene when AV1 format is not supported on user's browser.

[Vizualization] Better error message

---

lerobot/common/envs/utils.py

just a small fix in the assertion error message in the envs/utils.py. Seems the last and first channel was confused. The expected input image should have the channel dimension to be the last one not the first one.

small fix: assertion error message in envs/utils.py

---

lerobot/configs/default.yaml
lerobot/configs/env/aloha.yaml
lerobot/configs/env/xarm.yaml

Several people have reported issues with the PushT environment using asynchronous batches of envs. For example
```
gymnasium.error.NamespaceNotFound: Namespace gym_pusht not found. Have you installed the proper package for gym_pusht?
```
This PR switches back to no using async envs by default (which was the case most of the time but changed recently).

Don't use async envs by default

---

lerobot/common/robot_devices/cameras/opencv.py
tests/mock_opencv.py
tests/test_cameras.py
tests/utils.py

- Adds lock mechanism in `OpenCVCamera` for thread safe operation
- ~Adds `yield` in pytest monkeypatching fixture for cameras~ (actually doesn't work)
- Removes inheritance of `MockVideoCapture` from `cv2.VideoCapture`, which was causing ugly errors when trying to monkeypatch `cv2.VideoCapture` with it.
- Improve `MockVideoCapture` for more accurate behavior
- Use `np.testing.assert_allclose` instead of `assert np.allclose` for displaying errors nicely
TODO (this PR or another one):
Running `pytest -v -k "opencv" tests/test_cameras.py` doesn't raise any segmentation fault anymore, but does still raise assert errors on `np.allclose` (separate issue)
EDIT: For `mock=True` this is now fixed. It was caused by the monkeypatch not actually being applied and therefore was using the real camera …

Fix opencv segmentation fault

---

examples/9_use_aloha.md

The 9_use_aloha.md setup example was missing a comma so the shell cmd that installed dependencies wouldn't run without modification.
Was: 
```bash
cd ~/lerobot && pip install -e ".[dynamixel intelrealsense]"
```
Now:
```bash
cd ~/lerobot && pip install -e ".[dynamixel, intelrealsense]"
```

Update 9_use_aloha.md, missing comma

---

lerobot/common/robot_devices/robots/feetech_calibration.py

Examples:
Examples:
Examples:
```bash
DATA_DIR=tests/data pytest -sx tests/test_stuff.py::test_something
```
```bash
``` …

Fix autocalib moss

---

lerobot/scripts/find_motors_bus_port.py

Windows uses COM ports not what is expected for Linux/Mac. This commit adds support for Windows OS. It does this by: 
- checking to see if OS is Windows, or other
- if Windows, use a new process
- if other, use existing process 
There is a dependency (`pyserial`) but it is already in the environment so no changes there. Once the port is identified it can be added to the `.yaml` the same as it is today. Although it will be referenced differently (e.g., `COM7` vs. `/dev/ttyACM`) the rest of the functionality still works.
Successful in Windows environment, and theoretically won't affect others, but does need to be confirmed before merge.
No change to [existing process](https://github.com/huggingface/lerobot/blob/main/examples/10_use_so100.md#configure-the-motors). To use, simply execute the …

Add support for Windows

---

lerobot/common/datasets/utils.py

This PR resolves a bug in the LeRobot repository that causes an error when uploading a dataset to Huggingface on Windows due to a Unicode encoding issue. The problem arises because Windows, by default, uses cp1252 encoding, which cannot handle certain Unicode characters, such as emojis. The error is caused by the dataset card containing an emoji.
Error trace:
The error produced is 'Traceback (most recent call last):
File "D:\dev\lerobot\lerobot\scripts\control_robot.py", line 885, in <module>
record(robot, **kwargs)
File "D:\dev\lerobot\lerobot\scripts\control_robot.py", line 681, in record
push_dataset_card_to_hub(repo_id, revision="main", tags=tags)
File "D:\dev\lerobot\lerobot\scripts\push_dataset_to_hub.py", line 124, in push_dataset_card_to_hub
card.push_to_hub(repo_id=repo_id, …

bug causes error uploading to huggingface, unicode issue on windows.

---

lerobot/common/robot_devices/control_utils.py

| Fixes error in `sanity_check_dataset_name()`       | 🐛 Bug        |
There was a bug within the `sanity_check_dataset_name()` function. When the `control_robot.py` script was executed for evaluation and the repo-id did not start with "eval_" it was raising a wrong ValueError.
This caused some confusion because it was unclear that the prefix "eval_" is needed.
- Added distinction between two possible error cases and checked that evaluation works with policy act_so100_real on our own dataset.
Examples:
This should raise the right error message:
(Taken from the [SO-100 Guide](https://github.com/huggingface/lerobot/blob/main/examples/10_use_so100.md))
```bash
python lerobot/scripts/control_robot.py record \ …
```

Add distinction between two unallowed cases in name check "eval_"

---

lerobot/configs/policy/act_aloha_real.yaml
lerobot/configs/policy/act_koch_real.yaml
lerobot/configs/policy/act_moss_real.yaml
lerobot/configs/policy/act_so100_real.yaml

Renamed deprecated argument in Hydra config files to match torch implementation.
Should have been fixed here #319 (where act config was changed)
Renamed argument and checked that training converges with policy act_so100_real on own dataset.
```bash
DATA_DIR=data python lerobot/scripts/train.py \
dataset_repo_id=${HF_USER}/so100_test \
policy=act_so100_real \
env=so100_real \
hydra.run.dir=outputs/train/act_so100_test \
hydra.job.name=act_so100_test \
device=cuda \
wandb.enable=true
```
```bash
python lerobot/scripts/control_robot.py record \
--robot-path lerobot/configs/robot/so100.yaml \
--fps 30 \
--root data \
--repo-id ${HF_USER}/eval_act_so100_test \
--tags …
```

Rename deprecated argument (temporal_ensemble_momentum)

---

.github/workflows/test.yml
lerobot/scripts/control_robot.py
tests/test_control_robot.py

- Add `--local-files-only` for record/replay
1. Recorded 2 episodes without pushing on the hub
```bash
python lerobot/scripts/control_robot.py record \
--robot-path lerobot/configs/robot/so100.yaml \
--fps 30 \
--repo-id cadene/so100_5_lego_test \
--num-episodes 2 \
--warmup-time-s 5 \
--episode-time-s 60 \
--reset-time-s 30 \
--single-task "Pick up the lego blocks and put them in the box on the right side of the robot." \
--push-to-hub 0
```
2. Resumed recording and record 1 more episode:
```
python lerobot/scripts/control_robot.py record \
--robot-path lerobot/configs/robot/so100.yaml \
--fps 30 \
--repo-id cadene/so100_5_lego_test \
--num-episodes 1 \
--warmup-time-s 1 \
--episode-time-s 60 \
--reset-time-s 30 \
--single-task "Pick up the lego blocks and put them in the box on the …
```

Fix missing local_files_only in record/replay

---

lerobot/common/datasets/utils.py

Path to card_template.md passed in relation to the current location of the lerobot package.
In the previous version the path was served statically and relative to the current folder: `./lerobot/common/datasets/card_template.md` This creates problems when launching LerobotDataset.push_to_hub() outside of the package folder.
In the current version the path is provided in relation to the current path of the package: `importlib.resources.path("lerobot.common.datasets", "card_template.md")` This allows to execute the method `create_lerobot_dataset_card` from any folder. As long as Lerobot is installed.
On branch fix--dataset_push_to_hub
Changes to be committed:
modified:   lerobot/common/datasets/utils.py
| …

LerobotDataset pushable to HF from any folder

---

.pre-commit-config.yaml
examples/6_add_image_transforms.py
lerobot/common/datasets/image_writer.py
lerobot/scripts/control_sim_robot.py

- Fix example `6_add_image_transforms.py`: `lerobot/aloha_static_tape` hasn't been converted to v2 due yet to some problems with that particular dataset but was used in this example, which led to a compatibility error.
- Misc.: Ran `pre-commit autoupdate` and then `pre-commmit run -a`
Successfully ran example 6.
```bash
python examples/6_add_image_transforms.py
```

Fix example 6

---

examples/9_use_aloha.md
lerobot/common/robot_devices/control_utils.py

Fixing typo from 'teloperation' to 'teleoperation'.

fixing typo from 'teloperation' to 'teleoperation'

---

lerobot/common/policies/hilserl/classifier/configuration_classifier.py
lerobot/common/policies/hilserl/classifier/modeling_classifier.py
poetry.lock
pyproject.toml
tests/conftest.py
tests/policies/hilserl/classifier/check_hiserl_reward_classifier.py
tests/policies/hilserl/classifier/test_modelling_classifier.py

Add unit tests and check script for the Reward Classifier. Also, fixed small issue with imports.
- I have added unit tests for the reward classifier `/tests/policies/hilserl/classifier/test_modelling_classifier.py`. Run `python -m pytest -sv ./tests/policies/hilserl/classifier/test_modelling_classifier.py `
- Also I have added a script that trains and check metrics for the classifier, check - `python tests/policies/hilserl/classifier/check_hiserl_reward_classifier.py`. If u want to see a convergence for the model - choose bigger number of epoch in the file, check `EPOCH_NUM`, setup 30-40.
Examples:
```bash
python -m pytest -sv ./tests/policies/hilserl/classifier/test_modelling_classifier.py 
python …
```

[Port Hil-SERL] Add unit tests for the reward classifier & fix imports & check script

---

lerobot/common/policies/sac/modeling_sac.py

Fixes CI issues in the main port branch

[HIL-SERL PORT] Fix linter issues

---

lerobot/common/datasets/utils.py
tests/lerobot/common/datasets/test_utils.py

During the recording of dataset for HIL-SERL integration I have found the following issue:
```
Traceback (most recent call last):.93M/4.54M [00:01<00:00, 4.89MB/s]
File "/Users/helper2424/Documents/lerobot/lerobot/scripts/control_robot.py", line 577, in <module>      | 3/6 [00:03<00:04,  1.38s/it]
record(robot, **kwargs)███████████| 6/6 [00:03<00:00,  1.88it/s]
File "/Users/helper2424/Documents/lerobot/lerobot/common/robot_devices/utils.py", line 28, in wrapper
raise e
File "/Users/helper2424/Documents/lerobot/lerobot/common/robot_devices/utils.py", line 24, in wrapper
return func(robot, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/helper2424/Documents/lerobot/lerobot/scripts/control_robot.py", line 334, in record
dataset.push_to_hub(tags=tags)
File …
```

Fix broken `create_lerobot_dataset_card` 

---

.github/workflows/quality.yml

Hotfix for the Quality workflow which is currently broken due to the release of poetry 2.0.0.
Since we can't merge #621 for now, I'm pushing this fix until we're able to.
Quality workflow is [passing](https://github.com/huggingface/lerobot/actions/runs/12670288325/job/35309634575?pr=622)

Fix Quality workflow

---

benchmarks/video/README.md

- Fixes typos in the documentation:
- "accross" → "across"
- "should not be pose" → "should not pose"
- "appart" → "apart"
- "detailled" → "detailed"
- "appartment" → "apartment"
Tagging this PR as (🐛 Bug) since it addresses documentation errors.
- Manually inspected the updated documentation for the corrected spelling.
- Confirmed that references and functionality remain unaffected by the changes.
```bash
```

fix(docs): typos in benchmark readme.md

---

lerobot/scripts/visualize_dataset_html.py

When visualising datasets (v2) that contain a language instruction, the instruction of the first episode is always used. This is confusing when trying to use multi-task datasets, and this PR fixes it.
using the visualise dataset command.
visualise a dataset that contains different language descriptions, for example the following:
```bash
python lerobot/scripts/visualize_dataset_html.py --repo-id villekuosmanen/pick_up_lid
```

fix(visualise): use correct language description for each episode id

---

lerobot/common/datasets/v2/batch_convert_dataset_v1_to_v2.py

fix: typo "platic" to "plastic" in dataset descriptions  
Fixed typo in "aloha_static_vinh_cup" dataset description: "platic" -> "plastic"  
Fixed typo in "aloha_static_vinh_cup_left" dataset description: "platic" -> "plastic"  
This PR corrects a minor typo in the task descriptions for two datasets:  
- **"aloha_static_vinh_cup"**: Changed "platic" to "plastic"  
- **"aloha_static_vinh_cup_left"**: Changed "platic" to "plastic"  
These updates ensure the descriptions are accurate and professional. Tagging this as a **🐛 Bug** fix.
The changes were manually verified by reviewing the updated dataset descriptions to ensure the typo was corrected. No additional code was modified, so functionality remains unaffected.
1. Pull the branch with this fix.  
2. Open the affected dataset descriptions …

typo fix: batch_convert_dataset_v1_to_v2.py

---

lerobot/scripts/visualize_dataset_html.py
lerobot/templates/visualize_dataset_template.html

As Remi noted, viz was failing for [yaak-ai/lerobot-driving-school](https://huggingface.co/datasets/yaak-ai/lerobot-driving-school). 
The reason was: previously viz tool assumed float32 features to have exact names `observation.state` & `action`. However, [yaak-ai/lerobot-driving-school](https://huggingface.co/datasets/yaak-ai/lerobot-driving-school) had a field `action.continuous`.
This PR fixes this issue by removing hardcoded names `observation.state` & `action` in favour for dynamically selecting all `float32` features.

[viz] Fixes & updates to html visualizer

---

examples/10_use_so100.md

Fixes to the S0-100 instructions
- Mac: added Mac-specific instructions.  the previous instructions were only for Ubuntu
- readability: increased readability by using numbered lists and sublists (see below for before/after)
- links: links to youtube videos are to the exact sections of the video instead of to the start
- looked through README, made sure instructions made sense for both ubuntu and Mac
- I ran through and made the entire arm with a Mac using the README instructions
Possible reviewers: @jess-moss @Cadene @aliberts

fixes to SO-100 readme

---

lerobot/common/logger.py
lerobot/common/policies/hilserl/classifier/configuration_classifier.py
lerobot/common/policies/hilserl/classifier/modeling_classifier.py
lerobot/common/robot_devices/control_utils.py
lerobot/configs/policy/hilserl_classifier.yaml
lerobot/scripts/control_robot.py
lerobot/scripts/eval_on_robot.py
lerobot/scripts/train_hilserl_classifier.py
tests/test_train_hilserl_classifier.py

(A) This PR adds the possibility to train the reward classifier with multiple camera images. The architecture includes:
1- one pretrained resnet encoder for all images (with frozen parameters)
2- each image is passed through the encoder to get a compressed representation.
3- The representations are concatenated and passed through an MLP that will be trained to predict the reward. 
(B) This PR also extends the `eval_on_robot.py` script to load the reward classifier and the label each timestep with the predicted reward in real-time. 
(C) in `lerobot/common/robot_devices/control_utils.py` a new function to reset the follower arm to the initial position it was in at the start of the control. This is important for collecting a dataset with rewards so we don't get redundant frames in the …

Extend reward classifier for multiple camera views

---

lerobot/scripts/control_robot.py

When resuming a dataset creation, the reset environment code is skipped and this simple code change fixes the issue.
Simple fix for the issue reported in https://github.com/huggingface/lerobot/issues/638
I attempted the second step in the repro that was showing the unexpected behavior with my fix and now it's behaving as expected. The code change is simple, intuitive and likely the expected code.
Try the repro in the issue and then either checkout my branch or locally make the fix to verify.

Fix for the issue https://github.com/huggingface/lerobot/issues/638

---

lerobot/common/constants.py
lerobot/common/datasets/utils.py
lerobot/common/envs/configs.py
lerobot/common/envs/utils.py
lerobot/common/policies/act/modeling_act.py
lerobot/common/policies/diffusion/configuration_diffusion.py
lerobot/common/policies/diffusion/modeling_diffusion.py
lerobot/common/policies/factory.py
lerobot/common/policies/normalize.py
lerobot/common/policies/tdmpc/configuration_tdmpc.py
lerobot/common/policies/tdmpc/modeling_tdmpc.py
lerobot/common/policies/vqbet/configuration_vqbet.py
lerobot/common/policies/vqbet/modeling_vqbet.py
lerobot/common/utils/utils.py
lerobot/configs/policies.py
lerobot/configs/types.py
tests/test_policies.py

Add features back into policies configs

Add features back into policy configs

---

examples/10_use_so100.md
examples/11_use_moss.md
examples/7_get_started_with_real_robot.md
examples/8_use_stretch.md
examples/9_use_aloha.md
lerobot/common/robot_devices/cameras/intelrealsense.py
lerobot/common/robot_devices/cameras/opencv.py
lerobot/common/robot_devices/cameras/utils.py
lerobot/common/robot_devices/control_configs.py
lerobot/common/robot_devices/motors/dynamixel.py
lerobot/common/robot_devices/motors/feetech.py
lerobot/common/robot_devices/motors/utils.py
lerobot/common/robot_devices/robots/configs.py
lerobot/common/robot_devices/robots/manipulator.py
lerobot/common/utils/utils.py
lerobot/configs/eval.py
lerobot/scripts/control_robot.py
lerobot/scripts/train.py

Update robot examples with draccus commands

---

lerobot/scripts/visualize_dataset.py

This commit addresses several typos in `lerobot/scripts/visualize_dataset.py`:
- "doesnt" → "doesn't" (line 18)
- "lossly" → "lossy" (line 25)
- "repositery" → "repository" (line 202)
- Ran `python lerobot/scripts/visualize_dataset.py --repo-id lerobot/pusht --episode-index 0` locally to verify everything still works.
- Ran the test case of `lerobot/scripts/visualize_dataset.py` by running `pytest tests/test_visualize_dataset.py`.  
- However, the test function `test_visualize_local_dataset` is currently skipped via `@pytest.mark.skip("TODO: add dummy videos")`. The test file still ensures that we can import the relevant modules by `from lerobot.scripts.visualize_dataset import visualize_dataset` without error.
- You can review the updated docstrings and help texts to ensure the spelling …

Fix typos in `lerobot/scripts/visualize_dataset.py`

---

examples/7_get_started_with_real_robot.md
lerobot/scripts/configure_motor.py

Updates to `configure_motor.py` script and example 7 to provide correct motor configuration of dynamixels in a Koch 1v1 robot.
Example 7 now refers to the updated motor configuration script. Prior to this it referred to an outdated method of automatically running the configuration on connection.
The script to configure the motor now only sends Lock commands if the motor is a feetech, otherwise it skips the Lock.
I built my own Koch 1v1 and configured it using the above changes. Motors all took the updated baud rate and ID properly. Follower/leader motors work correctly.
Follow the updated instructions in `examples/7_get_started_with_real_robot.md` to configure a Koch 1v1 from scratch.
If you have a dynamixel disconnected from any robot, you could also just run something like this:
``` …
```

updating config instructions for koch 1v1 motors

---

lerobot/common/datasets/lerobot_dataset.py
tests/test_datasets.py

If you create a dataset with feature keys that contain a '/', this will work fine and you can store the dataset. However, the serialized dataset stats will be corrupt because [they are flattened](https://github.com/huggingface/lerobot/blob/4323bdce227fbe91e7fb28eaffd298034b7ffffa/lerobot/common/datasets/lerobot_dataset.py#L900) using a '/' as separator. Upon training, you will get 'keyErrors' as the original feature names are now no longer available in the dataset stats file.
This is rather annoying to debug when you start training, and at that point you have to recreate your datasets. 
This PR adds a simple check to guard against creating a dataset with features that contain a '/' in their key, to make sure this issues is caught upon creation of the dataset.
Explain/show how you tested …

Check for "/" in feature names

---

lerobot/common/datasets/transforms.py
poetry.lock
pyproject.toml

The recent release of torchvision [0.21](https://github.com/pytorch/vision/releases/tag/v0.21.0) breaks our nightly tests —which install the latest packages— due to some changes in the (internal) API.
This complies with the changes introduced in https://github.com/pytorch/vision/pull/8787 that are now in the 0.21.0 release.
⚠️ Since the design change is not backward compatible, this means we have to bump up the version requirement for torchvision. Users will have to update their env:
```bash
pip install torchvision>=0.21.0
poetry install --sync --all-extras
```
- PR tests are passing
- Successfully ran a [build](https://github.com/huggingface/lerobot/actions/runs/13059585390) and [nightly](https://github.com/huggingface/lerobot/actions/runs/13059973111) run on this branch.
```bash
pytest …
```

Comply with torchvision 0.21 custom transforms

---

lerobot/common/datasets/factory.py
lerobot/common/datasets/transforms.py
lerobot/common/policies/sac/configuration_sac.py
lerobot/common/policies/sac/modeling_sac.py

Adds a pretrained vision encoder from HF to the sac modeling + allows for appropriate transforms when training.
Ran a sac training with moss. 
My sac training script and associated modeling have slight differences, so it would be good to double check with a training loop incorporating real images and the current sac training script.

[Port HIL-SERL] Add HF vision encoder option in SAC

---

lerobot/scripts/configure_motor.py

Use the MotorBusConfig in the configure_motor.py script
This was tested on a FeeTech motor with the same command as in the documentation.

fix setting motor id with new dataclass config

---

docker/lerobot-cpu/Dockerfile
docker/lerobot-gpu/Dockerfile

Adds git lfs to nighlty test docker images which weren't pulling testing artifacts
`Build` and `Nightly` passing

Fix nightly tests docker images

---

lerobot/configs/policy/hilserl_classifier.yaml
lerobot/scripts/train_hilserl_classifier.py

We create custom Resnet 10. Need to compare inference perfomance between old encoder/Resnet10 and FB Convnet to chose the best one.
This PR adds ability to track inference time.
Examples:
Examples:
Examples:
```bash
pytest -sx …
```

[HIL-SERL port] Add Reward classifier benchmark tracking to chose best visual encoder

---

.github/workflows/quality.yml
.github/workflows/test-docker-build.yml
.github/workflows/test.yml

Update trigger rules on our CI so that workflows trigger on any PR and not just on ones pointing to main (as is currently the case)
N/A

Update CI trigger rules

---

lerobot/common/policies/pi0/modeling_pi0.py
lerobot/common/utils/wandb_utils.py
lerobot/scripts/train.py

- Fix the `.forward()` output format for Pi0 ([issue on discord](https://discord.com/channels/1216765309076115607/1237741463832363039/1339130881696202927))
- Various fixes for `WandBLogger` ([issue on discord](https://discord.com/channels/1216765309076115607/1237741463832363039/1339134743081517117))
Used this short run with wandb enabled to test out wandb fixes:
```python
python lerobot/scripts/train.py \
--policy.type=act \
--policy.dim_model=64 \
--policy.n_action_steps=20 \
--policy.chunk_size=20 \
--env.type=aloha \
--env.episode_length=5 \
--dataset.repo_id=lerobot/aloha_sim_transfer_cube_human \
--dataset.image_transforms.enable=true \
--dataset.episodes="[0]" \
--batch_size=2 \
--steps=4 \
--eval_freq=2 \
--eval.n_episodes=1 \
--eval.batch_size=1 \
--save_freq=2 \ …
```

Fixes following #670

---

lerobot/configs/train.py

Adds an exception raised if trying to resume a training run from the hub as this is not implemented for now.
The following correctly raises an error
```bash
python lerobot/scripts/train.py  \
--config_path=lerobot/diffusion_pusht \
--resume=true \
--steps=200000 \
--wandb.enable=false
```

Prevent resuming from hub

---

examples/port_datasets/pusht_zarr.py
lerobot/common/datasets/lerobot_dataset.py
lerobot/common/datasets/utils.py
lerobot/common/robot_devices/control_utils.py
lerobot/scripts/control_robot.py
tests/test_datasets.py

Motivations: We want to start supporting datasets with multiple tasks per episode. We also want to iterate on a simpler API for adding new frames to a dataset, where all features are added using `dataset.add_frame(frame: dict)`.
For instance:
- 2D features like a sequence of x,y positions (waypoints)
- string features like captions
TODO
- Ran `python examples/port_datasets/pusht_zarr.py`
- Ran tests
```bash
pytest -sx tests/test_datasets.py::test_add_frame
```

Add frame level task

---

lerobot/scripts/train.py

Fix wandb logging when the `output_dict` from the policy is `None` ([issue on discord](https://discord.com/channels/1216765309076115607/1237070292237422632/1339986785542996009))
Ran
```bash
python lerobot/scripts/train.py \
--config_path=lerobot/diffusion_pusht \
--job_name=fix_train_wandb \
--log_freq=1 \
--step=4 \
--eval_freq=2 \
--save_freq=2 \
--eval.n_episodes=1 \
--eval.batch_size=1 \
--env.episode_length=10
```

Fix wandb logging

---

examples/port_datasets/pusht_zarr.py
lerobot/common/datasets/lerobot_dataset.py
lerobot/common/datasets/utils.py
lerobot/scripts/control_robot.py
tests/fixtures/dataset_factories.py
tests/test_datasets.py

Consolidate was doing 3 things:
- Encoding videos from remaining images (if any) that were not encoded during `save_episode` -> Video are automatically encoded during save_episode
- Perform various sanity checks (number of files, timestamps sync) -> moved to `save_episode`
- Compute statistics ->  Removed by #521 
Normal testing suite

Remove dataset `consolidate`

---

lerobot/common/datasets/lerobot_dataset.py

Uploading ~100 GB datasets can crash with `hub_api.upload_folder`, which we currently use in `push_to_hub`.
However using `hub_api.upload_large_folder` allows to resume uploading if any crash occurs.
Uploading a 400GB dataset with it.

Add `upload_large_folder` argument in `push_to_hub`

---

examples/9_use_aloha.md

Fix the URL to setup hardware Aloha Stationary in the example document.
- from: https://docs.trossenrobotics.com/aloha_docs/getting_started/stationary/hardware_setup.html
- to: https://docs.trossenrobotics.com/aloha_docs/2.0/getting_started/stationary/hardware_setup.html
It is just a URL in the document.

Fix the URL to setup hardware Aloha Stationary in the example document

---

.github/workflows/pr_style_bot.yml
.github/workflows/quality.yml

Inspired by https://github.com/huggingface/diffusers/pull/10274
Allows to automatically apply styling on PRs by calling `@bot /style` in a comment.

Add pr style bot

---

lerobot/templates/visualize_dataset_template.html

Added pagination to episdoes list.
Problem description: for example dataset https://huggingface.co/datasets/cadene/droid has 90k episodes, which meant that UI was rendering 90k items, which caused the browser to slow down.
Solution: add pagination. At any given time, render only 1k episodes and users can go backward or forward (see attached img)
I've temporarily pushed this branch to https://huggingface.co/spaces/lerobot/visualize_dataset?dataset=cadene%2Fdroid&episode=89673 so that you can test 
Indeed, the performance is much better now

[vizualisation] Add pagination for many episodes

---

lerobot/scripts/visualize_dataset_html.py
lerobot/templates/visualize_dataset_template.html

Implemented columns having different names
I've temporarily pushed this branch to https://huggingface.co/spaces/lerobot/visualize_dataset?dataset=cadene%2Fdroid&episode=89673 so that you can test

[Vizualisation] independent column names

---

.github/workflows/pr_style_bot.yml

Fix pr_style_bot

---

lerobot/common/datasets/lerobot_dataset.py
lerobot/common/datasets/utils.py
lerobot/common/datasets/v21/convert_dataset_v20_to_v21.py

When using `LeRobotDataset.push_to_hub`, a version tag is not automatically created, making subsequent download of said dataset fail since we're looking for a compatible version tag.
- Added automatic codebase version tagging with `tag_version: bool = True` arg in `push_to_hub`.
- Added cleared error message and instructions when failed to retrieve any version tags.
Dataset uploaded with fix : [pepijn223/lekiwi_fix1](https://huggingface.co/datasets/pepijn223/lekiwi_fix1)

Fix dataset version tags

---

.pre-commit-config.yaml
lerobot/common/utils/utils.py
lerobot/scripts/eval.py
lerobot/scripts/visualize_dataset_html.py
lerobot/templates/visualize_dataset_template.html
pyproject.toml

Adds [Bandit](https://github.com/PyCQA/bandit) in pre-commits which is a security linter to detect common security issues in Python code.
Performs the following fixes to comply with the issues reported:
- Rename `eval` -> `eval_main` as bandit thinks this is python's built-in `eval` function (we should use builtins names anyway)
- Add a `timeout` value to some `requests.get` calls
- Replaced an `os.system` with the safer `subprocess.run(..., shell=False)`
- Other unrelated formatting fixes due to running `pre-commit run -a`
Deactivates a few rules after verification that this is reasonable given our usage:
- [B101](https://bandit.readthedocs.io/en/latest/plugins/b101_assert_used.html)
- [B311](https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b311-random)
- …

[Security] Add Bandit

---

examples/2_evaluate_pretrained_policy.py

(🐛 Bug) Commit 5e94738 induced a regression in example 2 by omitting to delete  `map_location` argument. This PR simply removes it.
My changes were tested by running  
```sh
python examples/2_evaluate_pretrained_policy.py
```
after a clean install.
Run 
```sh
python examples/2_evaluate_pretrained_policy.py
```
Before the modification, you should get:
```bash
TypeError: DiffusionPolicy.__init__() got an unexpected keyword argument 'map_location'
```

:bug: Remove `map_location=device` that no longer exists when loading DiffusionPolicy from_pretained after commit 5e94738

---

tests/test_policies.py

Fix [failing gpu nightly test](https://github.com/huggingface/lerobot/actions/runs/13712419454/job/38351282115)
Since we moved the `device` into the policy config, `PreTrainedPolicy.from_pretrained` returns the policy onto the `device` in `PreTrainedConfig`. This broke `tests/test_policies.py::test_save_and_load_pretrained` since loaded policy is loaded to the device while the first one default to cpu.
- sends first policy to correct device
- minor refactor on this test
- Ran [Build](https://github.com/huggingface/lerobot/actions/runs/13719471623) and [Nightly](https://github.com/huggingface/lerobot/actions/runs/13719628103) workflows on current branch

Fix gpu nightly

---

tests/test_policies.py

Deactivate tdmpc backward compatibility test with `use_mpc=True`
Ran [Build](https://github.com/huggingface/lerobot/actions/runs/13759133662) and [Nightly](https://github.com/huggingface/lerobot/actions/runs/13760233860) on current branch

Fix cpu nightly

---

lerobot/configs/policy/hilserl_classifier.yaml
lerobot/scripts/train_hilserl_classifier.py

1. Optimize the `create_balanced_sampler()` function for better efficiency. Instead of iterating through the entire dataset, I utilized Huggingface's `select()` method to obtain a subset of the dataset and retrieve the labels using the `label_key`.
-  I achieved a **1794x performance boost** (from 28.08 seconds to 0.015649 seconds) on a dataset containing 8121 samples.
2. Refactor the code to align with the structure of `train.py` and better organized output directories.

[Port HIL-SERL] Balanced sampler function speed up and refactor to align with train.py

---

.pre-commit-config.yaml

- Fixes a warning thrown by pre-commit about the typo hook rev (wasn't properly updated by `autoupdate`)
- Adds 2 [meta hooks](https://pre-commit.com/#meta-hooks)
- Prettify
Ran `pre-commit run -a`

Improve pre-commit config

---

lerobot/common/robot_devices/robots/manipulator.py

Use float32 instead of int32 in manipulator teleop and send_action to improve accuracy. As proposed in https://github.com/huggingface/lerobot/issues/552
Tested on so100 arms

Use float32 instead of int

---

lerobot/common/teleoperators/keyboard/teleop_keyboard.py

Replaces lock mechanism with a queue for the keyboard tele implementation
This is meant to be squash & merge

refactor(teleop): Use queue instead of locks for keyboard teleop

---

README.md

This PR fixes a spelling mistake in the installation instructions by correcting the spelling of ‘ffmpeg’.
This is a documentation update, so no testing was required.

fix(docs): correct spelling of 'ffmpeg' in installation instructions

---

lerobot/common/datasets/video_utils.py

Cast `imgs_dir` as `Path()`
```python
>>> import os
>>> from pathlib import Path
>>> imgs_dir: Path = os.getcwd()
>>> imgs_dir = Path(imgs_dir)
>>> str(imgs_dir / "frame_%06d.png")
'/Users/steven.palma/Documents/HF/projects/lerobot/frame_%06d.png'
```

fix(datasets): cast imgs_dir as Path

---

lerobot/scripts/server/buffer.py

When `optimize_memory=True`, the `ReplayBuffer` avoids redundant `next_state` storage by referencing `state[i+1]`. However, if the buffer is not full, sampling indices near `self.size` could reference uninitialized memory, leading to invalid `next_state` values (e.g., black images).
To address this, the sampling logic has been adjusted to:
- Restrict indices to valid transitions when the buffer is not full.
- Allow full sampling when the buffer is full (circular buffer behavior).
A training experiment was run, confirming no errors related to black images.

Fix: Prevent Invalid next_state References When optimize_memory=True

---

examples/11_use_lekiwi.md

MacOS does require to allow Terminal access keyboard otherwise python can not read keyboard.
- Run locally on a laptop with MacOs
Run the teleoperation for le kiwi on MacOs

docs: add tip for Mac users regarding Terminal permissions for keyboard

---

README.md
examples/7_get_started_with_real_robot.md

Restores a previously removed note ( #903 ) regarding `ffmpeg` installation with `conda`. If the required version (7.1.1) is not specified, an `conda` might install an older version by default. This led to some encoding/decoding issues during Mistral AI Robotics hackathon and even within LeRobot team.
On my own setup during installation (`conda install ffmpeg -c conda-forge`would default to on older version of `ffmpeg`), on several setups (macOS & Linux) during Mistral AI Robotics Hackathon.
N/A

fix(installation): adding note on `ffmpeg` version during installation

---

pyproject.toml

Context: The dependency manager currently picks up the latest `torchcodec` (released 20 minutes ago), which depends on yesterday’s `torch` release—the same version we restricted in: https://github.com/huggingface/lerobot/pull/1022
To maintain compatibility, we have this PR as a hotfix to pin `torchcodec` to `0.2.1` for now.
Next Steps:
1. Open a PR to relax constraints (both `torchcodec` and `torch`): https://github.com/huggingface/lerobot/pull/1029
2. Fix tests and ensure compatibility in #1029 with the latest versions.
3. Once CI passes, merge #1029 .
This is important because audio work will depend on the latest `torchcodec`

fix(ci): Pin `torchcodec` (==0.2.1) to fix pipeline temporarly

---

examples/12_use_so101.md

Add a table to explain in which order the STS3215 motors should be assembled for SO101 leader arm

Add description motor order SO-101 leader

---

lerobot/common/robot_devices/control_utils.py

As mention in  #1071, When I run control_robot.py record with --display_data=true option and policy, The process is failed caused by Exception. Because In control_utils.py control_loop method when called from warmup_record method, It is failed access action object.
I'm adding codes which create action object and if case to prevent this error in the control_loop method.
I've run test case without real robot on macOS. In polices testcase, some test cased failed due to mixed devices. but I believe this is problem of some settings to test case.
```
FAILED tests/policies/test_policies.py::test_policy[lerobot/pusht-pusht-env_kwargs1-diffusion-policy_kwargs1] - RuntimeError: Expected all tensors to be on the same device, but found at least two devices, mps:0 and cpu!
FAILED …
```

bug fix for #1071 When --display_data=true, Failed running control_robot.

---

lerobot/common/policies/smolvla/modeling_smolvla.py
lerobot/common/utils/wandb_utils.py

This PR fixes an issue where loss values from `SmolVLAPolicy` were not being logged to Weights & Biases (wandb) due to incompatible data types. The code previously attempted to log PyTorch tensors directly, which `wandb_utils.py` ignores. Now, `loss` stored in `loss_dict` is converted to Python scalars using `.item()` to ensuring proper logging.
The warning looks like:
```
WARNING 2025-06-04 01:51:55 db_utils.py:117 WandB logging of key "loss" was ignored as its type "<class 'torch.Tensor'>" is not handled by this wrapper.
```
There are similar warnings for `losses_after_forward`, `losses_after_in_ep_bound`, and `losses_after_rm_padding`, but they are lists. So I'll leave them alone for now.
- Manually ran training and verified that `loss` is now visible in the wandb dashboard.
- …

Fix SmolVLA loss not sent to wandb

---

lerobot/common/policies/pi0fast/modeling_pi0fast.py
lerobot/common/policies/smolvla/modeling_smolvla.py

Some files eg. lerobot/common/policies/pi0fast/modeling_pi0fast.py still refer to OBS_ROBOT instead of OBS_STATE. 
This PR replaces all references to OBS_ROBOT with OBS_STATE, to resolve errors when pi0fast or smolvla policies are used.

replaced OBS_ROBOT with OBS_STATE constant

---

pyproject.toml

Reverts some changes from #1208 as num2words and accelerate are actually needed to run smolVLA

Fix smolVLA dependencies

---

pyproject.toml

Moves `pyserial` dependency from test dependencies to global dependencies to avoid installation errors.

fix(pyserial): adding pyserial dependency to global ones

---

lerobot/common/policies/pi0/paligemma_with_expert.py
lerobot/common/policies/pi0fast/modeling_pi0fast.py
pyproject.toml

This pull request includes changes to ensure compatibility with different versions of the `transformers` library and updates the dependency constraints for `pi0`. The most important changes include adding conditional logic to handle varying `transformers` versions in image embedding methods and restricting the `transformers` version range in the `pyproject.toml`.
* [`lerobot/common/policies/pi0/paligemma_with_expert.py`](diffhunk://#diff-84a97b430342f7245243c2a9b28bdd365a8b4e9debfb55a32af5a6601a282d0cR219-R223): Updated the `embed_image` method to check if `paligemma` has a `get_image_features` method and fallback to `paligemma.model.get_image_features` if not. This ensures compatibility with different versions of the `transformers` library.
* …

fix: update pi0 dependency version constraint

---

examples/lekiwi/record.py
lerobot/common/robots/lekiwi/config_lekiwi.py
lerobot/common/robots/lekiwi/lekiwi.py
lerobot/common/robots/lekiwi/lekiwi_client.py
lerobot/common/robots/lekiwi/lekiwi_host.py

This PR changes the LeKiwi kinematics and motor naming to match the documentation and the rest of the code (mentioned on [Discord](https://discord.com/channels/1216765309076115607/1318390825528332371/1381835903965728898)). Issue arose from robots refactor. Additionally the camera rotations are fixed for LeKiwi as can be seen in the dataset visualizer, which shows a dataset recorded with the fixes.
Additionally I removed: `OBS_STATE` and `OBS_IMAGES` constants from lekiwi code to make it similar to other robots in the code base.
Tested 
- Teleoperation
- Dataset recording
Check: [dataset_visualizer](https://huggingface.co/spaces/lerobot/visualize_dataset?path=%2Fpepijn223%2Flekiwi1749634728%2Fepisode_0)

Match motor names with ids lekiwi

---

lerobot/common/policies/pretrained.py
lerobot/common/policies/smolvla/modeling_smolvla.py
pyproject.toml

This PR proposes a fix 
1. to tokenisation of 'task' in `modeling_smolvla.py` after refactoring. 
2. checkpoint keys mapping/mismatch associated with using smolvla on other robots (e.g. SO101) zero-shot without fine-tuning.

fix issues: checkpoints keys mismatch and 'task' tokenisation in smolvla

---

lerobot/common/datasets/v2/batch_convert_dataset_v1_to_v2.py
lerobot/common/policies/act/modeling_act.py
lerobot/common/policies/diffusion/configuration_diffusion.py
lerobot/common/policies/diffusion/modeling_diffusion.py
lerobot/common/policies/pi0fast/modeling_pi0fast.py
lerobot/common/policies/tdmpc/modeling_tdmpc.py
lerobot/common/policies/vqbet/modeling_vqbet.py
lerobot/common/policies/vqbet/vqbet_utils.py

Examples:
Examples:
Examples:
```bash
```
```bash
``` …

Use HF Papers

---

docs/source/getting_started_real_world_robot.mdx
lerobot/record.py

This allows to run `record.py` with a policy without the need of passing `teleop` CLI arguments + updates docs

fix(record): no teleop needed when running with policy

---

lerobot/common/teleoperators/so100_leader/so100_leader.py
lerobot/common/teleoperators/so101_leader/so101_leader.py

We print the path where the calibration was saved for the SO10* `robots`, we should do it also for the SO10* `teleop`

chore(teleop): print calibration path saved

---

pyproject.toml

Minor fix to support gamepad without installing `gym_hil`.
Addressing the comment in https://github.com/huggingface/lerobot/pull/644#discussion_r2145129302

chore(dependencies): add gamepad support with pygame and hidapi

---

docs/source/integrate_hardware.mdx

Various fixes on hardware integration tutorial (code examples, typos..)

Fixes on robot integration tutorial

---

lerobot/common/teleoperators/keyboard/__init__.py
lerobot/common/teleoperators/keyboard/configuration_keyboard.py
lerobot/common/teleoperators/keyboard/teleop_keyboard.py
lerobot/common/teleoperators/utils.py
lerobot/scripts/rl/gym_manipulator.py

Adds `KeyboardEndEffectorTeleop` as a child of the main keyboard teleop class that is designed to control the end effector of a manipulator in the style of the robot `SO100FollowerEndEffector`
**NOTE:** These additions have been tested on an so100 follower arm (teleoperated with my keyboard).
- Arrow keys: Move in X-Y plane
- Shift/Shift_R: Move in Z axis
- Right/Left Ctrl: Open/close gripper
- 'i': Toggle intervention mode
- 'f': End episode with failure
- 's': End episode with success
- 'r': End episode with rerecord
- `KeyboardEndEffectorTeleop` extends base teleop for end-effector specific control keys
- `KeyboardControlWrapper` integrates keyboard control into the gym environment in `gym_manipulator.py`
Test with gym manipulator by setting the teleop device in this [example …

Add keyboard teleop device to control the end effector robot 

---

lerobot/common/robots/robot.py
lerobot/common/teleoperators/teleoperator.py

The `Robot` base class currently type hints `config_class` as having the exact type `RobotConfig`. The issue with this is that super classes that inherit from `RobotConfig` aren't compatible with the type hint. However we want to accept classes that inherit from `RobotConfig`. With this PR we allow all classes which inherit from `RobotConfig`.
TLDR: Make `config_class` compatible with classes that inherit from `RobotConfig` to satisfy type checkers

Improve type hints

---

lerobot/scripts/rl/learner.py

Single line fix in `learner.py` to use `so101_leader` instead of `so100_leader`

`learner.py` import so101_leader instead of so100

---

lerobot/common/policies/pi0/paligemma_with_expert.py

This PR fixes bugs raising errors at forward using PI0.
This has been tested running inference. To reproduce this test (without needing to fine-tune your own PI0 model), use the following lines:
```python
from lerobot.common.policies.pi0.modeling_pi0 import PI0Policy
policy = PI0Policy.from_pretrained("fracapuano/pi0")  # use this, I have updated the expected keys in the observation
```
Then load a dataset and run inference. You can use this snippet to run an inference pipeline on a given dataset. **Important: use `lerobot/svla_so100_stacking`**
```python
from dataclasses import asdict
from lerobot.common.datasets.lerobot_dataset import LeRobotDataset
import torch
from lerobot.common.policies.pi0.configuration_pi0 import PI0Config
from lerobot.common.policies.pi0.modeling_pi0 import …
```

Fixing `PI0` Policy

---

lerobot/scripts/rl/gym_manipulator.py

Single line fix in `gym_manipulator.py`
Remove the condition to have a None value for your leader intervention actions that can cause a bug when trying to record a dataset for the RL with the leader in `record_dataset` function. 
Nowhere do we expect that action_intervention to be None as that is governed by the `is_intervention` bool. Therefore, this won't have any backward effect on the code.

`gym_manipulator.py` Remove None value action_intervention of BaseLeaderTeleoperator

---

docs/source/il_robots.mdx

Fixes incorrect documentation for resuming dataset recording. The docs incorrectly stated `--control.resume=true` when the actual parameter is `--resume=true` according to the code implementation in `RecordConfig`.
Label: (🐛 Bug)
- Verified the correct parameter name in the `RecordConfig` class in `lerobot/record.py`
- Confirmed that `resume: bool = False` is a direct field, not under a `control` section
Review the documentation change and optionally test the recording resume functionality:
This should work after the fix:
```bash
python -m lerobot.record --resume=true [other parameters...]
```
This would fail (the old incorrect documentation)
```bash
python -m lerobot.record --control.resume=true [other parameters...]
```

Fix incorrect --resume parameter in recording documentation

---

README.md

pkg-config appears twice in the package list.
minor doc fix
Just ran it in my prompt to confirm
review the before and after.  
```bash
sudo apt-get install cmake build-essential python3-dev pkg-config libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev libswresample-dev libavfilter-dev pkg-config
```
does the same thing as 
```bash
sudo apt-get install cmake build-essential python3-dev pkg-config libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev libswresample-dev libavfilter-dev
```

There can be only one!!

---

lerobot/common/robots/so101_follower/so101.mdx

Update docs to match what setup motors sript outputs: 
== LEADER
python -m lerobot.setup_motors --teleop.type=so101_leader --teleop.port=/dev/tty.usbmodem5A680087821
Connect the controller board to the 'gripper' motor only and press enter.
'gripper' motor id set to 6
Connect the controller board to the 'wrist_roll' motor only and press enter.
'wrist_roll' motor id set to 5
Connect the controller board to the 'wrist_flex' motor only and press enter.
'wrist_flex' motor id set to 4
Connect the controller board to the 'elbow_flex' motor only and press enter.
'elbow_flex' motor id set to 3
Connect the controller board to the 'shoulder_lift' motor only and press enter.
'shoulder_lift' motor id set to 2
Connect the controller board to the 'shoulder_pan' motor only and press enter.
'shoulder_pan' …

Update assembly instructions to match outputs from 'python -m lerobot.setup_motors' script

---

pyproject.toml

Pip install of lerobot is currently broken, see https://github.com/huggingface/lerobot/issues/1427

Update pyproject.toml to make package installable with pip

---

src/lerobot/policies/act/modeling_act.py
src/lerobot/policies/diffusion/modeling_diffusion.py
src/lerobot/policies/normalize.py
src/lerobot/policies/pi0/modeling_pi0.py
src/lerobot/policies/pi0fast/modeling_pi0fast.py
src/lerobot/policies/sac/modeling_sac.py
src/lerobot/policies/smolvla/modeling_smolvla.py
src/lerobot/policies/tdmpc/modeling_tdmpc.py
src/lerobot/policies/vqbet/modeling_vqbet.py

Applies a very minor fix on top of all policies running inference, to make sure CUDA memory consumption is limited at inference time (ensured via the `@torch.no_grad()` decorator---wrongly added as `@torch.no_grad` and now fixed).

Fixes `@torch.no_grad()` usage

---

src/lerobot/utils/utils.py

This PR improves the `init_logging()` utility function by fixing the logging level setting (not working in the current state) and adding separate arguments for setting console and file logging levels.
Features were tested using the following Python script :
```python
import logging
from lerobot.utils.utils import init_logging
init_logging(log_file = "loggging.txt", console_level = "INFO", console_level = "DEBUG")
logging.debug("This is a debug log message.")
logging.info("This is a test log message.")
logging.warning("This is a warning log message.")
logging.error("This is an error log message.")
logging.critical("This is a critical log message.")
```

fix(logging): Fixing logging levels

---

pyproject.toml
tests/async_inference/test_e2e.py
tests/async_inference/test_policy_server.py
tests/async_inference/test_robot_client.py

- Make tests skip-able with `pytest.importorskip("grpc")` and `requires_package` decorator for minimal tests
- Move imports, that implicitly import grpc to inside the test functions

Attempt to fix async test

---

src/lerobot/scripts/server/policy_server.py

In the async inference PR (#1196), there's some randn noise injected to all the actions (https://github.com/huggingface/lerobot/commit/2425f6c215d95e7d39309af1ed316c54c8c70e00#diff-e6c27e873b6aab1af2879dc3bc4787516b513eb8bfffe8996de6b28109cf35beR326). This seems to be leftover from testing. This PR removes it.
Before this change, there's very jerky movement: https://discord.com/channels/1216765309076115607/1343589494485553222/1393108733487480853
After this change, the jerky movement is gone.
Follow the async inference instructions: https://huggingface.co/docs/lerobot/en/async

[Async Inference] Remove random noise injected by policy server

---

src/lerobot/configs/policies.py

Currently, it's not possible to specify policy overrides for training when using `--policy.path`. The error looks like:
```
> python -m lerobot.scripts.train \
--dataset.repo_id="${DATASET_REPO_ID}" \
--policy.path=lerobot/smolvla_base \
--policy.repo_id="${POLICY_REPO_ID}" \
--output_dir="${OUTPUT_DIR}" \
--job_name="${POLICY_REPO_ID}_${CLUSTER_NAME}" \
--policy.device=cuda \
--policy.optimizer_lr="1e-3" \
--wandb.enable=true \
--wandb.disable_artifact=true \
--wandb.notes="${WANDB_NOTES}" \
--num_workers=8 \
--batch_size="${BATCH_SIZE}" \
--steps="100_000" \
--save_freq="5_000"
...
unrecognized arguments: --optimizer_lr=1e-3
```
This PR resolves this by doing another hack on top of the existing hack to:
1. find the subclass of `PreTrainedConfig`.
2. parse the config file into the …

Parse draccus subclass overrides when using `--policy.path`

---

.cache/calibration/so100/main_follower.json
.cache/calibration/so100/main_leader.json
lerobot/common/datasets/profile_streaming_dataset.py
lerobot/common/datasets/streaming_dataset.py
lerobot/common/datasets/utils.py

Part of PR stack
👉 https://github.com/huggingface/lerobot/pull/1173
👀 https://github.com/huggingface/lerobot/pull/1165
👀 https://github.com/huggingface/lerobot/pull/969
This PR extends `StreamingLeRobotDataset` to support delta timestamps, enabling efficient access to past and future frames during streaming without loading the entire dataset into memory.
- **Bidirectional buffering**: Maintains separate buffers for history (`_back_buf`) and lookahead (`_ahead_buf`)
- **Configurable windows**: Set `history` and `lookahead` parameters to control buffer sizes. These parameters are inferred automatically from the input `delta_timesteps` according to a worst-case-scenario logic (min and max delta values, respectively).
- **Memory efficient**: Only keeps necessary frames in memory based on …

Add support for delta timesteps streaming

---

.github/workflows/test-docker-build.yml
docker/Dockerfile.internal
docker/Dockerfile.user
pyproject.toml

This PR is part of a series of future improvements to build a reliable system and infrastructure that lets us publish new releases with confidence. This takes care of:
* Updating Dockerfiles images to be used in the future by the CI workflows.
* Updating `pyproject.toml` accordingly.
We'll use these files after refactoring our CI workflows, which will likely involve removing the current Dockerfiles. Why not edit the existing ones now? Because I want to keep the current CI functioning as-is until the workflow refactoring is complete. Reviewing these now will help us focus solely on the CI changes when they're ready.
As these files are not yet used, it is safe to review them individually.

feat(ci): add new & clean Dockerfiles

---

src/lerobot/robots/so101_follower/so101.mdx

Updating docs as I found placing cables afterwards cumbersome.

Advise placement of cable during assembly, clarify USB instructions

---

src/lerobot/policies/pi0/modeling_pi0.py
src/lerobot/policies/pi0fast/modeling_pi0fast.py

Add a disclaimer when running from_pretrained so it's clear that the model will behave differently to the one on openpi

Add disclaimer to pi0 from_pretrained

---

.github/workflows/full_tests.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
Makefile
docker/Dockerfile.internal

This PR is part of a series of future improvements to build a reliable system and infrastructure that lets us publish new releases with confidence. This takes care of:
* Adding a Github CI workflows for creating a GH Release (and a PyPI release in the future)
* For now we manually bump the `pyproject.toml` version + manually create & push a tag of the form of `v*.*.*` in `main`
* Once the tag has been pushed, the release workflow will trigger: does a sanity check on the version number, build the wheels, creates a GH release, automates the release notes and uploads the assets.
We don't publish to PyPI yet due to the following reasons: 
* We need to properly configure the entry points for the main CLI scripts we provide (like `lerobot.teleoperate`)
* We need to configure the `__init__` root …

feat(ci): add release workflow

---

.pre-commit-config.yaml

Small fixes on the pre-commit config:
- `typos` need to be used through a mirror in order for the autoupdate bot to work properly (see https://github.com/crate-ci/typos/issues/390)
- Replace the `prettier` mirror with a non-archived one that only points to actual prettier releases

Pre-commits fixes

---

.github/workflows/full_tests.yml
.github/workflows/release.yml
pyproject.toml

This PR is part of a series of future improvements to build a reliable system and infrastructure that lets us publish new releases with confidence. This takes care of:
* Adds (optional) entry points for common scripts in the package
* Does sanity checks for the versioning of the release
* Adds minimal testing for post-release
* Enables publishing to PyPI job
* Ideally we would wait for https://github.com/huggingface/lerobot/pull/1570 to kick the first release
Some TODOs for future PRs:
* Tag documentation with the same tag
* Create a workflow for testing the release pipeline on a weekly basis & publishing in test pypi
* Consider alpha/pre-release or rc tagging

feat(ci): add entrypoints + add version checks + add minimal release testing + uncomment publishing to pypi

---

src/lerobot/envs/configs.py

Although not affecting the execution, the typing in some of  the fields in `config.py` are actually wrong.
For example, the task field in subclass of `EnvConfig` are typed inconsistently, leading the basedpyright warning:
```
basedpyright: "task" overrides symbol of same name in class "EnvConfig"
Variable is mutable so its type is invariant
Override type "str" is not the same as base type "str | None"
[reportIncompatibleVariableOverride]
```
Secondly, the override of `gym_kwargs` in `HILSerlRobotEnvConfig` miss the property decorator, leading the following linter problem:
```
basedpyright: "gym_kwargs" incorrectly overrides property of same name
in class "EnvConfig" [reportIncompatibleMethodOverride]
```
This commit enforces more strict typing on this file.

fix(config): typing correction on config.py

---

pyproject.toml

This PR fixes CI failure caused by missing wheels in the latest `v.0.21.4` release of `tokenizers`.
N/A
N/A

fix(tokenizers dependency): adding ceiling version on tokenizers

---

pyproject.toml

Removing ceiling versions on `tokenizers` and `huggingface_hub` dependencies after patch release and wheels publication.
N/A
N/A

fix(dependencies): removing versions ceilings on tokenizers and huggingface_hub dependencies

---

README.md

This PR fixes a typo in one of the authors' names in LeRobot citation.

fix(typo): fixing typo in LeRobot authors names

---

src/lerobot/processor/__init__.py
src/lerobot/processor/device_processor.py
src/lerobot/processor/normalize_processor.py
src/lerobot/processor/observation_processor.py
src/lerobot/processor/pipeline.py
src/lerobot/processor/rename_processor.py
tests/processor/test_observation_processor.py
tests/processor/test_pipeline.py

This PR does the following:
* Make sure `EnvTransition` typed dict uses the keys defined in `TransitionKey` for consistency
* Update minor things in the docstrings
* Remove `seed` from the `RobotProcessor`
* Remove `reset_hooks`
* Remove profilling methods
* `VanillaObservationProcessor` & `RenameProcessor` inherits from `ObservationProcessor`
* Add check for `device` in `DeviceProcessor`
* Remove `ImageProcessor` & `StateProcessor`, now these functionalities are directly implemented in `VanillaObservationProcessor`
* Remove `eps` in `UnnormalizerProcessor`
* Update the tests accordingly

refactor(pipeline): minor improvements

---

pyproject.toml

Recent releases of `torch` and `torchvision` (and soon `torchcodec`) are causing CI failures. This PR temporarily caps these dependencies to unblock CI for other PRs.
Additionally, since new releases often break our tests, we may want to keep these version limits permanently to prevent issues with our PyPI package releases.

fix(deps): ceil torch pkg versions

---

docker/Dockerfile.user

`python:${PYTHON_VERSION}-slim` base image tag we use for `Dockerfile.user`, transitioned from Debian 12 "Bookworm" to Debian 13 "Trixie". In Trixie, the `libegl1-mesa` package is not longer available, but we can use `libegl-mesa-dev` instead.
CI Nightly test: https://github.com/huggingface/lerobot/actions/runs/16960539630

fix(ci): rename libegl1-mesa in deb13 trixie

---

src/lerobot/processor/normalize_processor.py
src/lerobot/processor/rename_processor.py
src/lerobot/record.py
tests/processor/test_normalize_processor.py
tests/processor/test_rename_processor.py

* Delete `un/normalized_info` as it just adds complexity for a not so valuable observability
* Reduce greatly duplicated code between the implementations of the Un/Normalize ProcessorSteps

refactor(processor): improvements normalize pipeline migration

---

src/lerobot/datasets/lerobot_dataset.py

(🐛 Bug) 
This PR fixes a bug in the `LeRobotDataset.save_episode` method where the `episode_data` parameter was ignored when provided.
Previously, the method's logic did not correctly handle the `episode_data` parameter. This would cause an error if `self.episode_buffer` was not the intended data source, for instance, in an asynchronous data recording scenario.
The change ensures that if `episode_data` is passed, it is used as the source for saving the episode. Otherwise, it defaults to `self.episode_buffer` as before.
This fix is crucial for enabling non-blocking, asynchronous data recording. Users can now pass a copy of the episode buffer to this method for saving, while the main buffer is immediately cleared to continue collecting new data without being blocked by I/O operations.
The …

fix(dataset): Correctly use episode_data parameter in save_episode

---

tests/processor/test_batch_processor.py

We have removed support for in-place modification, so we have updated the test.

chore(tests): update ToBatchProcessor test

---

examples/phone_to_so100/evaluate.py
examples/phone_to_so100/record.py
src/lerobot/datasets/utils.py
tests/datasets/test_dataset_utils.py

- Updated references in evaluate.py, record.py, and test_dataset_utils.py to reflect the new function name.
- Improved code readability and maintainability by standardizing the naming convention.

refactor(datasets): rename merge_features to merge_dataset_features for clarity

---

src/lerobot/teleoperators/phone/teleop_phone.py

- Updated method names in IOSPhone and AndroidPhone classes to improve readability and maintainability.
- Ensured consistent naming convention across teleoperation modules.

chore(teleoperators): rename _wait_for_capture_trigger to _capture_calibration_pose_on_trigger for clarity

---

src/lerobot/processor/converters.py
src/lerobot/processor/gym_action_processor.py
src/lerobot/processor/normalize_processor.py
tests/processor/test_converters.py
tests/processor/test_normalize_processor.py

- Introduced `to_tensor` function using `singledispatch` to handle various input types, including scalars, arrays, and dictionaries, converting them to PyTorch tensors.
- Replaced previous tensor conversion logic in `gym_action_processor`, `normalize_processor`, and `test_converters` with the new `to_tensor` function for improved readability and maintainability.

refactor(converters): implement unified tensor conversion function

---

examples/phone_to_so100/evaluate.py
examples/phone_to_so100/record.py
examples/phone_to_so100/replay.py
examples/phone_to_so100/teleoperate.py
src/lerobot/processor/converters.py
src/lerobot/record.py
src/lerobot/replay.py
src/lerobot/teleoperate.py
tests/processor/test_converters.py

* chore(processor): rename `to_transition_teleop_action` -> `action_to_transition`
* chore(processor): rename `to_transition_robot_observation` -> `observation_to_transition`
* chore(processor): rename `to_output_robot_action` -> `transition_to_robot_action`

chore(processor): rename converters function names

---

examples/phone_to_so100/evaluate.py
examples/phone_to_so100/record.py
examples/phone_to_so100/replay.py
examples/phone_to_so100/teleoperate.py
src/lerobot/policies/act/processor_act.py
src/lerobot/policies/diffusion/processor_diffusion.py
src/lerobot/policies/factory.py
src/lerobot/policies/pi0/processor_pi0.py
src/lerobot/policies/pi0fast/processor_pi0fast.py
src/lerobot/policies/sac/processor_sac.py
src/lerobot/policies/sac/reward_model/processor_classifier.py
src/lerobot/policies/smolvla/processor_smolvla.py
src/lerobot/policies/tdmpc/processor_tdmpc.py
src/lerobot/policies/vqbet/processor_vqbet.py
src/lerobot/processor/__init__.py
src/lerobot/processor/migrate_policy_normalization.py
src/lerobot/processor/normalize_processor.py
src/lerobot/processor/pipeline.py
src/lerobot/record.py
src/lerobot/replay.py
src/lerobot/teleoperate.py
src/lerobot/utils/control_utils.py
src/lerobot/utils/train_utils.py

- Split pipelines: implement `RobotProcessorPipeline` and `PolicyProcessorPipeline` type aliases to clearly delineate responsibilities.
- Implement separate pipelines `RobotProcessorPipeline` and `PolicyProcessorPipeline `to clarify each pipeline’s role.

chore(processor): add type alias RobotProcessorPipeline and PolicyProcessorPipeline

---

src/lerobot/processor/converters.py
src/lerobot/record.py

Tests `test_record_and_resume` and `test_record_and_replay` were failing with:
```
ValueError: Feature mismatch in `frame` dictionary:
Extra features: {'next.truncated', 'next.reward', 'next.done'}
```
**Root cause**: `transition_to_dataset_frame` was adding `next.*` fields to frames during recording, but these features weren't included in the dataset's expected features definition.
1. **Added missing features** (`record.py`): Include `next.reward`, `next.done`, `next.truncated` in dataset features with consistent `shape=(1,)` format
2. **Enhanced conversion logic** (`converters.py`): Made `transition_to_dataset_frame`  convert scalars to arrays only when target features expect `shape=(1,)`

fix(record): Add missing transition features (next.reward, next.done, next.truncated) to dataset recording

---

pyproject.toml
src/lerobot/robots/so100_follower/robot_kinematic_processor.py
src/lerobot/utils/rotation.py

This PR removes the scipy dependency from the robot kinematic processor by implementing a custom `Rotation` class that provides identical functionality to `scipy.spatial.transform.Rotation` for the specific use cases in this codebase.
- **`src/lerobot/utils/rotation.py`**: Custom `Rotation` class implementation
- `from_rotvec()` - Initialize from rotation vectors using Rodrigues' formula
- `from_matrix()` - Initialize from 3x3 rotation matrices using Shepperd's method  
- `from_quat()` - Initialize from quaternions
- `as_matrix()` - Convert to 3x3 rotation matrix
- `as_rotvec()` - Convert to rotation vector
- `as_quat()` - Get quaternion representation
- **`src/lerobot/robots/so100_follower/robot_kinematic_processor.py`**: 
- Updated import: `from scipy.spatial.transform import Rotation` …

refactor(processor): Remove scipy dependency: Replace spatial.transform.Rotation with custom implementation

---

examples/phone_to_so100/evaluate.py
examples/phone_to_so100/record.py
src/lerobot/processor/converters.py
src/lerobot/record.py
src/lerobot/teleoperate.py
src/lerobot/utils/visualization_utils.py
tests/utils/test_visualization_utils.py

Simplified `log_rerun_data` to only accept observation and action dicts, reducing complexity from 76 to 41 lines.
**Changes:**
- Removed complex EnvTransition handling and heuristics
- Updated 2 call sites to extract obs/action data before calling function

refactor(utils): simplify log_rerun_data function

---

src/lerobot/robots/bi_so100_follower/config_bi_so100_follower.py
src/lerobot/robots/hope_jr/config_hope_jr.py
src/lerobot/robots/koch_follower/config_koch_follower.py
src/lerobot/robots/lekiwi/config_lekiwi.py
src/lerobot/robots/so100_follower/config_so100_follower.py
src/lerobot/robots/so101_follower/config_so101_follower.py
src/lerobot/robots/stretch3/configuration_stretch3.py
src/lerobot/robots/utils.py
src/lerobot/robots/viperx/config_viperx.py

This PR updates the robot configurations so that `max_relative_target` can be a float instead of just an integer.
This PR also makes a couple of small related changes:
- Updates the documentation for `max_relative_target`. Currently, it states that it can be a list of numbers, but the implementation of `ensure_safe_goal_position` only allows `max_relative_target` to be a scalar or a dictionary.
- Removes `max_relative_target` from `Stretch3RobotConfig`. `Stretch3Robot` does not use `max_relative_target`.
- Fixed an incorrect type annotation in `ensure_safe_goal_position`: `dict[float]` -> `dict[str, float]`.
Fixes #1716 and fixes #1527.
I have an SO-101 and tested this change by running lerobot-teleoperate under 4 conditions:
- `--robot.max_relative_target 10`
- Manually verified that …

Allow max_relative_target to be a float

---

src/lerobot/robots/koch_follower/koch_follower.py
src/lerobot/teleoperators/koch_leader/koch_leader.py

Disable torque before applying calibration logic for koch arms. While the dynamixel motors are in torque mode, it seems that writing to it does not work. This control path is executed when we decide to call `lerobot-calibrate` and not calibrating. 
```
File "/Users/stevengong/Projects/lerobot/src/lerobot/robots/koch_follower/koch_follower.py", line 120, in calibrate
self.bus.write_calibration(self.calibration)
File "/Users/stevengong/Projects/lerobot/src/lerobot/motors/dynamixel/dynamixel.py", line 195, in write_calibration
self.write("Homing_Offset", motor, calibration.homing_offset)
File "/Users/stevengong/Projects/lerobot/src/lerobot/motors/motors_bus.py", line 1023, in write
self._write(addr, length, id_, value, num_retry=num_retry, raise_on_error=True, err_msg=err_msg)
File …
```

fix (koch): Disable motor torque before applying calibration logic

---

src/lerobot/envs/utils.py
src/lerobot/scripts/eval.py
src/lerobot/scripts/train.py

- Updated the `rollout` and `eval_policy` functions to accept preprocessor and postprocessor parameters, enhancing the flexibility of the evaluation pipeline.
- Adjusted the implementation to apply preprocessing and postprocessing steps during policy evaluation, improving the overall data handling and processing flow.
Examples:
| Optimizes something | (⚡️ Performance) |
Examples:
- Optimized …

refactor(eval): integrate preprocessor and postprocessor into rollout and eval_policy functions

---

src/lerobot/processor/converters.py
src/lerobot/processor/normalize_processor.py
tests/processor/test_normalize_processor.py

- Updated the function name from _from_tensor to from_tensor_to_numpy to better reflect its purpose of converting PyTorch tensors to numpy arrays or scalars.
- Adjusted all references to the renamed function throughout the codebase to maintain consistency.
- Enhanced the _NormalizationMixin class to reconstruct the stats dictionary from tensor stats using the new function, ensuring compatibility after loading state dicts.
- Added tests to verify the correct reconstruction of stats and functionality of methods dependent on self.stats after loading.
Examples:
| Optimizes something | …

fix(normalizer_processor): reconstruct the stats dictionary from tensor stats

---

src/lerobot/policies/act/processor_act.py
src/lerobot/policies/diffusion/processor_diffusion.py
src/lerobot/policies/pi0/processor_pi0.py
src/lerobot/policies/pi0fast/processor_pi0fast.py
src/lerobot/policies/sac/processor_sac.py
src/lerobot/policies/smolvla/processor_smolvla.py
src/lerobot/policies/tdmpc/processor_tdmpc.py
src/lerobot/policies/vqbet/processor_vqbet.py
tests/processor/test_act_processor.py
tests/processor/test_diffusion_processor.py
tests/processor/test_pi0_processor.py
tests/processor/test_sac_processor.py
tests/processor/test_smolvla_processor.py
tests/processor/test_tdmpc_processor.py
tests/processor/test_vqbet_processor.py

- Moved DeviceProcessorStep to the end of the output steps in multiple processor files to maintain the intended processing order.
- Updated corresponding tests to reflect the change in step order.

performance(processor): reorder output steps to improve performance

---

src/lerobot/processor/pipeline.py
tests/processor/test_act_processor.py
tests/processor/test_batch_processor.py
tests/processor/test_classifier_processor.py
tests/processor/test_device_processor.py
tests/processor/test_diffusion_processor.py
tests/processor/test_migration_detection.py
tests/processor/test_normalize_processor.py
tests/processor/test_pipeline.py
tests/processor/test_pipeline_from_pretrained_helpers.py
tests/processor/test_rename_processor.py
tests/processor/test_sac_processor.py
tests/processor/test_tdmpc_processor.py
tests/processor/test_tokenizer_processor.py
tests/processor/test_vqbet_processor.py

Add intelligent migration detection to `DataProcessorPipeline.from_pretrained()` to guide users when they try to load old LeRobot models that need migration to the new processor format. During implementation, we discovered opportunities to dramatically simplify the loading logic by requiring explicit `config_filename` parameter.
- **ProcessorMigrationError**: Custom exception with actionable migration guidance
- **Smart detection**: Analyzes JSON configs to detect old LeRobot models requiring migration
- **Precise targeting**: Avoids false positives on other HuggingFace model types
- **Clear guidance**: Provides exact migration command to run
```python
DataProcessorPipeline.from_pretrained("old-lerobot-model", config_filename="config.json") …
```

feat(processor): implement migration detection and error handling for  processor configurations

---

docs/source/libero.mdx

For best performance, we should always load the VLM weights instead of training the backbone from scratch.
Another option is to update the smolvla config so that this is set to `true` by default

docs(fix): libero example command

---

README.md

Fixed broken link in the *Visualize datasets* section reference to one of the example notebooks.
Folder structure of examples seems to have changed with extra `dataset` folder and the notebook has also changed names.
Fixing the readme link to the example doc - the folder structure for exmaples changed  so `/examples/1_load_lerobot_dataset.py` --> `examples/dataset/load_lerobot_dataset.py`

Update README.md to fix broken link to example notebook for visuals

---

src/lerobot/datasets/video_utils.py

Remove extra time_base assignment that was causing issues in av versions < 15.

Fix pyav time_base error
