huggingface/lerobot

lerobot/common/policies/factory.py

Makes it possible to override policy config parameters at eval time with eval.py. See the discussion here for a real use case: https://github.com/huggingface/lerobot/pull/146#pullrequestreview-2044816980.
I ran `python lerobot/scripts/eval.py -p lerobot/diffusion_pusht eval.n_episodes=10 eval.batch_size=10 policy.num_inference_steps=3` and verified that the eval runs way faster.

Override pretrained model config

---

docker/lerobot-gpu/Dockerfile

Change docker image so that we can develop with it
Using the regular testing suite
```bash
docker build --build-arg PYTHON_VERSION=3.10 -t lerobot-gpu -f docker/lerobot-gpu/Dockerfile .
docker run --shm-size "16gb" --gpus "all" -ti lerobot-gpu:latest
```

Update dev docker build

---

lerobot/common/policies/act/configuration_act.py
lerobot/configs/policy/act.yaml

Explain why n_encoder_layers=1

---

Makefile
lerobot/configs/default.yaml
lerobot/configs/policy/tdmpc.yaml
lerobot/scripts/train.py

This PR disables online training as it wasn't working anyway, and we are adding new features that demand us to maintain it. This [branch](https://github.com/alexander-soare/lerobot/tree/train_tdmpc) has some fixes which are a work in progress.

Disable online training

---

lerobot/common/datasets/push_dataset_to_hub/aloha_dora_format.py
lerobot/scripts/push_dataset_to_hub.py

- Add `aloha_dora_format.py` to push data collected from real-world robot Aloha2 with Dora-rs
- This feature is in Alpha. We will iterate on it a bit.
TODO in future PR:
- improve `push_dataset_to_hub.py` API inspired by https://github.com/huggingface/lerobot/pull/221/files#diff-3bd4335afd38b4bb74c5dbbd99ab3e2bc52aaeebb0e120f14934f6102e0aa24b
- Add rigorous testing when we are happy with the API.
- Recorded `data/wrist_gripper_raw` with Dora-rs
- Converted it to LeRobotDataset format and pushed it to the hub: https://huggingface.co/datasets/cadene/wrist_gripper
- Trained a real-world model (with a PR to come)
- Evaluated the model on real robot
- Verified behavior is as expected: https://x.com/RemiCadene/status/1795370586069500069
```python
from huggingface_hub import snapshot_download …
```

Add `aloha_dora_format.py`

---

lerobot/common/datasets/push_dataset_to_hub/aloha_dora_format.py
lerobot/common/envs/factory.py
lerobot/configs/default.yaml
lerobot/configs/env/aloha.yaml
lerobot/configs/env/pusht.yaml
lerobot/configs/env/xarm.yaml
lerobot/scripts/train.py

- Refactor env to add key word arguments from config yaml
- (This is to prepare for real world policies)
CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/huggingface/lerobot/223)

Refactor env to add key word arguments from config yaml

---

tests/test_datasets.py

As the title suggests.
`DATA_DIR="tests/data" pytest tests/test_datasets.py -vv`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/huggingface/lerobot/230)

Add a test for MultiLeRobotDataset making sure it produces all frames.

---

lerobot/scripts/eval.py

Fixes second part of https://github.com/huggingface/lerobot/pull/244#issuecomment-2148334928
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/huggingface/lerobot/247)

Fix videos_dir documentation

---

docker/lerobot-cpu/Dockerfile
docker/lerobot-gpu/Dockerfile

Fix nightly tests by adding ffmpeg to docker images
Ran a full [build](https://github.com/huggingface/lerobot/actions/runs/9518219032) & [test](https://github.com/huggingface/lerobot/actions/runs/9518368261) cycle successfully
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/huggingface/lerobot/273)

Fix nightlies

---

lerobot/common/policies/factory.py
lerobot/configs/policy/diffusion.yaml
lerobot/configs/policy/tdmpc.yaml
tests/scripts/save_policy_to_safetensors.py
tests/test_policies.py

Add test to make sure policy dataclass configs match yaml configs

---

README.md

This PR adds new credits for the VQ-BeT policies, and citation for diffusion policy, ACT/Aloha, TDMPC, and VQ-BeT. The citations were taken from the websites where applicable, and google scholar otherwise.
No code changes, and thus N/A.
N/A.

Added new credits and citations

---

lerobot/common/policies/vqbet/configuration_vqbet.py
lerobot/common/policies/vqbet/modeling_vqbet.py
lerobot/common/policies/vqbet/vqbet_utils.py

- Add copyright mentions in VQ-BeT files
N/A
N/A

Add VQ-BeT copyrights

---

lerobot/scripts/train.py

Improve error message when attempting to overwrite a training output folder

---

lerobot/common/policies/diffusion/modeling_diffusion.py

Minimal adjustement, corrects the description of the timestamps used in Diffusion Policy
N/A.

Adjust the timestamps' description in Diffusion Policy

---

examples/7_get_started_with_real_robot.md

Examples:
Examples:
Examples:
```bash
DATA_DIR=tests/data pytest -sx tests/test_stuff.py::test_something
```
```bash
``` …

Add tutorial for real robot (DynamixelMotorsBus, OpenCVCamera, KochRobot, control_robot.py)

---

README.md

This small PR updates the README installation instructions to improve compatibility across different operating systems (macOS, Linux, and Windows, including PowerShell).  Powershell doesn't like the && symbols and will error.   The changes include:
1. Splitting the git clone and cd commands into separate lines for better clarity and compatibility with PowerShell.
2. Separating the conda create and conda activate commands for the same reason.
These modifications ensure that the installation process works smoothly on Mac, Linux, and Windows (including both Command Prompt and PowerShell).
| Label:  | 📝 Documentation|
The updated commands were tested on the following environments:
- Windows Command Prompt
- …

Update README for cross-platform installation compatibility

---

examples/7_get_started_with_real_robot.md
lerobot/common/datasets/utils.py
lerobot/scripts/control_robot.py
lerobot/scripts/push_dataset_to_hub.py

Adds dataset cards to our LeRobot datasets on the hub.
This will allow the community to easily find and gather open datasets created with LeRobot (either via `push_dataset_to_hub.py` or with `control_robot.py`) by labeling them.
To find them: https://huggingface.co/datasets?other=LeRobot
Example of a default dataset card pushed with `push_dataset_card_to_hub`:
```
---
task_categories:
- robotics
tags:
- LeRobot
---
This dataset was created using [🤗 LeRobot](https://github.com/huggingface/lerobot).
```
TODO in this PR:
```python
from huggingface_hub import HfApi
from tqdm import tqdm
from lerobot.common.datasets.lerobot_dataset import CODEBASE_VERSION
from lerobot.scripts.push_dataset_to_hub import push_dataset_card_to_hub
api = HfApi()
datasets_info = api.list_datasets(author="lerobot") …
```

Add dataset cards

---

lerobot/common/policies/vqbet/modeling_vqbet.py

Addresses https://github.com/huggingface/lerobot/issues/348
`python lerobot/scripts/eval.py -p lerobot/vqbet_pusht eval.use_async_envs=true eval.n_episodes=50 eval.batch_size=50`

Fix input dim

---

README.md
examples/7_get_started_with_real_robot.md

See file changes
Images are now in table format, instead of taking the full page.
https://github.com/huggingface/lerobot/blob/fc8f1429735d100c4712adb394b6097a99579e20/examples/7_get_started_with_real_robot.md

Slightly improve tutorial and README

---

lerobot/templates/visualize_dataset_template.html

Closes https://github.com/huggingface/lerobot/issues/366
Changed the html/js code so that it waits for all the videos to load before autoplaying.
cc: @aliberts @Cadene

Fix videos in visualize_dataset are not in sync

---

lerobot/scripts/visualize_dataset_html.py

rm unusued EpisodeSampler from`scripts/visualize_dataset_html.py`
cc: @Cadene @aliberts

rm EpisodeSampler from viz

---

lerobot/templates/visualize_dataset_template.html

Follow up to https://github.com/huggingface/lerobot/pull/382

[Visualization tool] Fix videos sync

---

examples/7_get_started_with_real_robot.md
lerobot/common/robot_devices/robots/manipulator.py
lerobot/common/robot_devices/utils.py
lerobot/configs/robot/aloha.yaml

Add comments for Aloha

---

lerobot/scripts/control_robot.py

- When data recording with aloha, a few seconds after end of warmup, the fps of all cameras were going from 30 Hz to 1 Hz, causing very laggy video.
- Fixed the issue by using `--num-image-writers 16` instead of `8` by default.
- To avoid having to change `--num-image-writers`, this PR updates it to `--num-image-writers-per-camera` with `4` by default. It is backward compatible with Koch robot and fixes Aloha automatically.
- This PR also updates the display of low fps in yellow. Instead of display the full line in yellow, when the global teleop fps is too low, we now highlight only the robot device with lower fps.
- Tested with `--num-image-writers-per-camera 4` (total number of threads = 16 -> expected high fps )
- Tested with `--num-image-writers-per-camera 2` (total number of threads …

Fix slow camera fps with Aloha

---

lerobot/common/datasets/utils.py

Fix dataset card

---

.dockerignore

BUILD: https://github.com/huggingface/lerobot/actions/runs/11211757613
NIGHTLY: https://github.com/huggingface/lerobot/actions/runs/11211922557

Fix nightly by updating .cache in dockerignore

---

examples/10_use_so100.md

I assume it should have been so100

Fix config file

---

lerobot/common/policies/sac/configuration_sac.py
lerobot/common/policies/sac/modeling_sac.py

This PR wants to solve importing RLPD in https://github.com/huggingface/lerobot/issues/504. It sets up the network architecture used in RLPD, including critic, critic ensembles, target critic, actor, and Lagrange network
It has not been tested yet, will test once all finished
**Note**: Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR. Try to avoid tagging more than 3 people.

Port SAC WIP

---

docker/lerobot-gpu-dev/Dockerfile

Fix cluster image

---

lerobot/common/robot_devices/control_configs.py

Fix --control.policy.path

---

lerobot/scripts/train.py

Fix train real world

---

docker/lerobot-cpu/Dockerfile
docker/lerobot-gpu-dev/Dockerfile
docker/lerobot-gpu/Dockerfile

Fixes docker builds
Images are building.

Fix Docker cpu/gpu builds

---

lerobot/common/policies/hilserl/classifier/configuration_classifier.py
lerobot/common/policies/sac/configuration_sac.py
lerobot/configs/policy/hilserl_classifier.yaml

Add resnet-10 as default encoder for HIL-SERL
Examples:
Examples:
```bash
```
```bash
```
**Note**: Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR. Try to avoid tagging more than 3 people.
**Note**: Before submitting this PR, please read the [contributor …

[Port HIL-SERL] Add resnet-10 as default encoder for HIL-SERL

---

.github/workflows/build-docker-images.yml
.github/workflows/nightly-tests.yml
.github/workflows/quality.yml
.github/workflows/test-docker-build.yml
.github/workflows/test.yml
.github/workflows/trufflehog.yml
.pre-commit-config.yaml

Adds [zizmor](https://github.com/woodruffw/zizmor) in pre-commits which is a tool to help find security issues in GitHub Actions CI/CD setups.
Consequentially, fixed all issues pointed out by this new tool.
All workflows still running properly

Add zizmor pre-commit

---

examples/port_datasets/pusht_zarr.py
lerobot/common/constants.py
lerobot/common/datasets/lerobot_dataset.py
tests/fixtures/constants.py
tests/test_datasets.py

- Use [`HF_HOME`](https://huggingface.co/docs/huggingface_hub/package_reference/environment_variables#hfhome)
- Rename `LEROBOT_HOME` -> `HF_LEROBOT_HOME` (exception raised if `LEROBOT_HOME` is set)
Normal testing suite

Use `HF_HOME` env variable

---

lerobot/common/datasets/compute_stats.py

Compute stats over big images takes too much time. Thus we downsample the images to reach a width or height ~= 150.
Before, computing the stats was taking 12 seconds on 100 images of shape 3x1080x1920:
```python
import numpy as np
import timeit
images = np.random.randint(0, 255, size=(100, 3, 1080, 1920), dtype=np.uint8)
print(timeit.timeit(lambda : images.max(axis=(0,2,3)), number=5))
print(timeit.timeit(lambda : images.min(axis=(0,2,3)), number=5))
print(timeit.timeit(lambda : images.mean(axis=(0,2,3)), number=5))
print(timeit.timeit(lambda : images.std(axis=(0,2,3)), number=5))
```
Now the same images are resized to 3x90x160 and it takes 0.25 seconds:
```python
downsample_factor = 12
down_images = images[:, :, ::downsample_factor, ::downsample_factor]
print(down_images.shape) …
```

Add auto downsample height width of images in compute_stats

---

.github/workflows/pr_style_bot.yml

Fixes permissions for the pr_style_bot workflow

Fix pr_style_bot

---

.github/workflows/pr_style_bot.yml

Fix pr_style bot

---

.github/workflows/pr_style_bot.yml

Ensures only admins / maintainers can trigger the style bot (copies https://github.com/huggingface/diffusers/pull/10931)

[CI] Update Stylebot Permissions

---

examples/3_train_policy.py

Fixes example3
Before the fix running `python3 examples/3_train_policy.py` results in:
```bash
Traceback (most recent call last):
File "/PATH/lerobot/examples/3_train_policy.py", line 106, in <module>
main()
File "/PATH/lerobot/examples/3_train_policy.py", line 88, in main
batch = {k: v.to(device, non_blocking=True) for k, v in batch.items()}
^^^^
AttributeError: 'list' object has no attribute 'to'
```
After the fix the example finishes successfully
Checkout the branch and run: `python3 examples/3_train_policy.py  `

fix(examples): Add Tensor type check

---

lerobot/scripts/visualize_dataset_html.py
lerobot/templates/visualize_dataset_template.html

[visualization] Ignore 2d or 3d data for now 
Test it here: 
I've temporarily pushed this branch to https://huggingface.co/spaces/lerobot/visualize_dataset?dataset=yaak-ai%2Flerobot-driving-school&episode=0 so that you can test

[visualization] Ignore 2d or 3d data for now

---

lerobot/common/robot_devices/robots/mobile_manipulator.py

Change the code so
- y axis if forward/backwards
- x axis is left/right
Motor angles are measured ccw from y axis for kinematics.

change wheel setup in kinematics

---

pyproject.toml

Removes hydra listed as a dependency

chore(deps): remove hydra dependency

---

README.md
examples/10_use_so100.md
examples/11_use_lekiwi.md
examples/11_use_moss.md
examples/4_train_policy_with_script.md
examples/7_get_started_with_real_robot.md
examples/9_use_aloha.md

Updates the instructions to reflect the changes in https://github.com/huggingface/lerobot/pull/812

chore(docs): update instructions for change in device and use_amp

---

lerobot/scripts/server/learner_server.py

Examples:
Examples:
Examples:
```bash
```
```bash
``` …

[PORT HIL-SERL] Optimize training loop, extract config usage

---

README.md
examples/10_use_so100.md
examples/11_use_lekiwi.md
examples/11_use_moss.md
examples/2_evaluate_pretrained_policy.py
examples/7_get_started_with_real_robot.md
examples/8_use_stretch.md
examples/9_use_aloha.md
lerobot/common/policies/pi0/modeling_pi0.py

Updates the documentation guiding the user to install the dependencies we need to install `lerobot`. Relates to: https://github.com/huggingface/lerobot/pull/907#issuecomment-2756195210

chore(docs): update docs

---

.pre-commit-config.yaml

See https://github.com/crate-ci/typos/issues/390

Switch typos pre-commit to mirror

---

lerobot/common/envs/configs.py
lerobot/common/policies/sac/configuration_sac.py
lerobot/common/policies/sac/modeling_sac.py
lerobot/common/robot_devices/control_utils.py
lerobot/scripts/control_robot.py
lerobot/scripts/server/actor_server.py
lerobot/scripts/server/buffer.py
lerobot/scripts/server/end_effector_control_utils.py
lerobot/scripts/server/gym_manipulator.py
lerobot/scripts/server/learner_server.py
lerobot/scripts/server/maniskill_manipulator.py

Examples:
Examples:
Examples:
```bash
```
```bash
``` …

[WIP] HIL SERL port grasp critic

---

lerobot/configs/train.py

Examples:
Examples:
Examples:
```bash
```
```bash
``` …

Fixup linter

---

docs/source/assemble_so101.mdx
docs/source/index.mdx

Fix code for embedded video's in docs + adapt readme

Docs: adapt text + fix video code

---

lerobot/common/datasets/utils.py
lerobot/common/policies/reward_model/configuration_classifier.py
lerobot/common/policies/reward_model/modeling_classifier.py
lerobot/scripts/server/gym_manipulator.py
tests/policies/hilserl/test_modeling_classifier.py

Branched from and completes the PR initated by @s1lent4gnt #1054 
Fixes docstrings in gym manipulator for the evaluation of the reward classifier

[Port HIL-SERL] Final fixes for reward classifier

---

lerobot/scripts/server/hilserl.proto
pyproject.toml

Examples:
Examples:
Examples:
```bash
```
```bash
``` …

Fixup proto header

---

lerobot/common/policies/sac/configuration_sac.py
lerobot/common/policies/sac/modeling_sac.py
tests/policies/test_sac_config.py
tests/policies/test_sac_policy.py

Examples:
Examples:
Examples:
```bash
```
```bash
``` …

[PORT HIL-SERL] Better unit tests coverage for SAC policy

---

docs/source/installation.mdx
examples/12_use_so101.md

Add -e for Feetech install commands in docs

Add editable -e for feetech install command

---

examples/11_use_moss.md
lerobot/common/datasets/image_writer.py
lerobot/common/datasets/lerobot_dataset.py
lerobot/common/datasets/video_utils.py
lerobot/common/policies/pi0/modeling_pi0.py
lerobot/common/policies/pi0fast/modeling_pi0fast.py

fix: typos and grammar

---

docs/source/_toctree.yml
docs/source/backwardcomp.mdx

Add docs on backward compatibility details from PR #777

feat(docs): add docs on backward compatibility

---

examples/lekiwi/evaluate.py

Fix `examples/lekiwi/evaluate.py` and addresses [this comment](https://github.com/huggingface/lerobot/pull/1194#discussion_r2126458882)

Fix LeKiwi example

---

docs/source/cameras.mdx
lerobot/find_cameras.py

Updates realsense camera documentation to latest imports path

fix(docs): update realsense documentation

---

lerobot/common/policies/sac/configuration_sac.py
lerobot/common/transport/utils.py
lerobot/common/utils/queue.py
lerobot/scripts/rl/actor.py
lerobot/scripts/rl/learner.py
lerobot/scripts/rl/learner_service.py
tests/rl/test_learner_service.py
tests/transport/test_transport_utils.py
tests/utils/test_queue.py

Examples:
Examples:
Examples:
```bash
```
```bash
``` …

[PORT HIL-SERL] Address comments for queues infra

---

lerobot/common/policies/smolvla/modeling_smolvla.py

Skip normalization parameters when loading pretrained smolVLA in order to keep normalization from fine-tuning dataset

Skip normalization parameters in load_smolvla

---

lerobot/common/robots/lekiwi/lekiwi.mdx

Add the --robot.id to the host cmd line.
Update the docs for lekiwi
Read the preview documentation
Check out the preview

Update lekiwi.mdx 

---

pyproject.toml

Bumps `transformers` to `4.50.3`, cc. @imstevenpmwork @AdilZouitine for visibility

bump `pi0` and `hil` transformers version

---

src/lerobot/scripts/server/configs.py
src/lerobot/scripts/server/constants.py
src/lerobot/scripts/server/helpers.py
src/lerobot/scripts/server/policy_server.py
src/lerobot/scripts/server/robot_client.py

refactor(async): drops argparse in favor of draccus

---

src/lerobot/scripts/server/configs.py
src/lerobot/scripts/server/helpers.py
src/lerobot/scripts/server/policy_server.py
src/lerobot/scripts/server/robot_client.py
tests/async_inference/test_e2e.py
tests/async_inference/test_policy_server.py
tests/async_inference/test_robot_client.py

refactor(async): multiple minor fixes

---

src/lerobot/utils/utils.py

Fix logging, 1 liner.
**Note**: Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR. Try to avoid tagging more than 3 people.
**Note**: Before submitting this PR, please read the [contributor guideline](https://github.com/huggingface/lerobot/blob/main/CONTRIBUTING.md#submitting-a-pull-request-pr).

Fix logging for mps in auto_select_torch_device

---

lerobot/common/datasets/aggregate.py
lerobot/common/datasets/utils.py
tests/datasets/test_aggregate.py

- This PR fixes issues with multiple datasets aggregation (changes in `aggregate.py`)
- Further, it also adds multiple tests to validate different aspects of datasets aggregation under two main scenarios (1) normal aggregation and (2) forced file-rotation, testing aggregation under unrealistically low thresholds to force multiple files creation
cc. @Cadene for review 🙏

Fix Aggregation, Add Tests

---

pyproject.toml

Updated version to identify breaking change introduced in #1417. I think minor bump is right for pre-stable, but don’t have strong feelings about what version is used (only need version to increment for dependency identity)
n/a
https://semver.org/

chore: bump lerobot project version to 0.2.0

---

src/lerobot/policies/smolvla/modeling_smolvla.py

Examples:
| Optimizes something | (⚡️ Performance) |
Examples:
Examples:
```bash
```
```bash
python -m lerobot.scripts.train --some.option=true
```
**Note**: Anyone in the community is free to review the PR once the …

smolfix(vla): typing and fix offline inference when action in the batch

---

docs/source/hilserl.mdx
docs/source/il_robots.mdx
docs/source/lekiwi.mdx
src/lerobot/__init__.py
src/lerobot/robots/viperx/README.md
tests/async_inference/test_robot_client.py

This PR updates the docs regarding the `resume` argument in `lerobot.record` and properly updates deprecated links.
N/A
N/A

docs/style: updating docs and deprecated links

---

src/lerobot/policies/diffusion/modeling_diffusion.py
src/lerobot/policies/tdmpc/modeling_tdmpc.py
src/lerobot/policies/vqbet/modeling_vqbet.py

Examples:
| Optimizes something | (⚡️ Performance) |
Examples:
Examples:
```bash
```
```bash
python -m lerobot.scripts.train --some.option=true
```
**Note**: Anyone in the community is free to review the PR once the …

fix(policies): remove action from batch for offline evaluation

---

src/lerobot/policies/pi0/modeling_pi0.py
src/lerobot/policies/smolvla/modeling_smolvla.py

some fixes that were missed in #1605

Fix sample beta for smolvla as done for pi0, remove sample_beta function refs

---

.github/workflows/release.yml
src/lerobot/calibrate.py
src/lerobot/find_cameras.py
src/lerobot/find_port.py
src/lerobot/record.py
src/lerobot/replay.py
src/lerobot/scripts/eval.py
src/lerobot/scripts/train.py
src/lerobot/setup_motors.py
src/lerobot/teleoperate.py

This fixes the entry-points declarations and the testing of the release

fix(ci): declare entrypoints + fix testing release

---

.github/workflows/release.yml

fix(ci): change steps based on wheter it is a -rc tag

---

pyproject.toml

chore(ci): Bump to v0.3.0

---

.github/workflows/release.yml
pyproject.toml

* remove `uv run` 
* bump pyproject minor version

fix(ci): remove uv run + bump minor

---

.github/workflows/release.yml
pyproject.toml

* Creates a venv for the release testing
* Bumps to 0.3.2

fix(ci): create venv for release testing

---

src/lerobot/policies/smolvla/modeling_smolvla.py
src/lerobot/policies/smolvla/processor_smolvla.py

- Removed the prepare_language method and directly accessed language tokens and masks from the batch using the OBS_LANGUAGE constant.
- Added SmolVLANewLineProcessor to ensure tasks end with a newline, enhancing tokenization compatibility.
- Updated the make_smolvla_processor function to include the new line processor and tokenizer processor for improved input handling.
Examples:
| Optimizes something | (⚡️ Performance) |
Examples:
- Added `new_feature` and checked that training converges …

feat(smolvla): Refactor language processing

---

src/lerobot/configs/policies.py
tests/policies/test_policies.py

Fixes https://github.com/huggingface/lerobot/issues/1664
Running:
```
pytest tests/policies/test_policies.py::test_multikey_construction
```

Fix policy construction

---

pyproject.toml

* Upgrades project's version to 0.3.3 for patch release

chore: Bump to 0.3.3

---

src/lerobot/processor/delta_action_processor.py

* `position_magnitude` is now the euclidean distance of the deltas
* noise threshold is now a configuration parameter and 1 mm
* remove unnecessary casts

refactor(processor): euclidean distance in delta action processor

---

src/lerobot/processor/hil_processor.py

* add missing `terminate_on_success` config to processor
* replace unsafe float comparison

fix(processors): fix float comparison and config in hil processors

---

docs/source/_toctree.yml
docs/source/feetech.mdx

This PR adds docs on how to upgrade your Feetech motors firmware

Add feetech firmware update docs

---

src/lerobot/constants.py
src/lerobot/datasets/pipeline_features.py
src/lerobot/processor/converters.py
src/lerobot/processor/hil_processor.py
src/lerobot/processor/tokenizer_processor.py
src/lerobot/robots/so100_follower/robot_kinematic_processor.py

- Added new constants for truncated and done states in constants.py.
- Updated references to action and observation keys in pipeline_features.py, converters.py, hil_processor.py, tokenizer_processor.py, and robot_kinematic_processor.py to use the new constants for improved readability and maintainability.

refactor(constants, processor): standardize action and observation keys across multiple files

---

src/lerobot/processor/converters.py
src/lerobot/processor/gym_action_processor.py
src/lerobot/processor/normalize_processor.py
tests/processor/test_converters.py
tests/processor/test_normalize_processor.py

Reverts huggingface/lerobot#1830

Revert "refactor(converters): implement unified tensor conversion function"

---

src/lerobot/processor/hil_processor.py
src/lerobot/robots/so100_follower/robot_kinematic_processor.py

update transition handling in RewardClassifierProcessor and InverseKinematicsEEToJoints for in-place modification

refactor(processors): update transition handling in RewardClassifierProcessor and InverseKinematicsEEToJoints

---

src/lerobot/processor/tokenizer_processor.py

- rename `_tokenizer` field to `input_tokenizer`

chore(processor): rename tokenizer field to input tokenizer

---

src/lerobot/teleoperators/phone/teleop_phone.py

Rename of internal variables at phone_teleop files

chore(processor): rename teleop_phone variable names

---

src/lerobot/processor/pipeline.py
src/lerobot/record.py
src/lerobot/teleoperate.py

fix(processor): recover type inference for use of processors

fix(processor): recover type inference for use of processors

---

src/lerobot/processor/hil_processor.py
src/lerobot/teleoperators/phone/phone_processor.py

chore(processor): remove action prefixes

chore(processor): remove action prefixes

---

examples/phone_to_so100/record.py
src/lerobot/datasets/utils.py
src/lerobot/processor/pipeline.py
src/lerobot/record.py
src/lerobot/robots/so100_follower/robot_kinematic_processor.py
src/lerobot/teleoperators/phone/phone_processor.py

fix(processor): phone examples

fix(processor): phone examples

---

examples/phone_to_so100/replay.py
src/lerobot/processor/__init__.py
src/lerobot/processor/factory.py
src/lerobot/record.py
src/lerobot/replay.py
src/lerobot/teleoperate.py

refactor(processors): move processors out of configs

refactor(processors): move processors out of configs

---

examples/phone_to_so100/evaluate.py
examples/phone_to_so100/record.py
src/lerobot/processor/__init__.py
src/lerobot/processor/factory.py
src/lerobot/record.py
src/lerobot/replay.py

chore(processor): streamline combine_features_dict

chore(processor): streamline combine_features_dict

---

src/lerobot/constants.py
src/lerobot/policies/pi0/modeling_pi0.py
src/lerobot/policies/smolvla/modeling_smolvla.py

chore(policies): use new constants

chore(policies): use new constants

---

pyproject.toml
src/lerobot/scripts/eval.py

fix(deps): right version transformers

fix(deps): right version transformers

---

src/lerobot/datasets/pipeline_features.py
tests/async_inference/test_helpers.py

fix(tests): add none + disable async tests for now

fix(tests): add none + disable async tests for now

---

src/lerobot/processor/delta_action_processor.py
src/lerobot/robots/so100_follower/robot_kinematic_processor.py
src/lerobot/teleoperators/phone/phone_processor.py

refactor(processor): transform_features loop + EAFP

refactor(processor): transform_features loop + EAFP

---

docs/source/koch.mdx
docs/source/lekiwi.mdx
docs/source/smolvla.mdx
docs/source/so100.mdx
docs/source/so101.mdx

fix(docs): update outdated links

fix(docs): update outdated links

---

docs/source/il_robots.mdx
examples/lekiwi/evaluate.py
examples/lekiwi/record.py
examples/lekiwi/teleoperate.py
examples/phone_to_so100/evaluate.py
examples/phone_to_so100/record.py
examples/phone_to_so100/teleoperate.py
examples/so100_to_so100_EE/evaluate.py
examples/so100_to_so100_EE/record.py
examples/so100_to_so100_EE/teleoperate.py
src/lerobot/scripts/lerobot_record.py
src/lerobot/scripts/lerobot_teleoperate.py
src/lerobot/utils/robot_utils.py
src/lerobot/utils/train_utils.py
src/lerobot/utils/utils.py
src/lerobot/utils/visualization_utils.py

chore(utils): remove unused utils legacy functions + rename init_rerun

chore(utils): remove unused utils legacy functions + rename init_rerun

---

src/lerobot/datasets/factory.py
src/lerobot/processor/converters.py
src/lerobot/rl/buffer.py
src/lerobot/rl/crop_dataset_roi.py
src/lerobot/rl/gym_manipulator.py
src/lerobot/scripts/lerobot_dataset_viz.py
src/lerobot/scripts/lerobot_eval.py
tests/datasets/test_datasets.py
tests/policies/hilserl/test_modeling_classifier.py
tests/processor/test_batch_conversion.py
tests/processor/test_converters.py
tests/processor/test_pipeline.py
tests/utils/test_replay_buffer.py

chore: replace hard-coded next values with constants throughout all the source code

chore: replace hard-coded next values with constants throughout all the source code

---

src/lerobot/rl/crop_dataset_roi.py

Save Cropped Dataset to Hub

---

.github/workflows/unbound_deps_tests.yml
docker/Dockerfile.internal
docker/Dockerfile.user
pyproject.toml

* chore(deps): ceil dependency versions
* feat(ci): new workflow for unbound dependencies testing

feat(deps): ceil dependency versions

---

docs/source/async.mdx
src/lerobot/async_inference/constants.py
src/lerobot/async_inference/helpers.py
src/lerobot/async_inference/policy_server.py
src/lerobot/async_inference/robot_client.py
tests/async_inference/test_e2e.py
tests/async_inference/test_helpers.py
tests/async_inference/test_policy_server.py

This PR adds the pipeline to async inference thereby fixing the current implementation.
This PR also updates the docs with the correct commands.
Related issues:
- Addressing: https://github.com/huggingface/lerobot/issues/2120 and https://github.com/huggingface/lerobot/issues/2119
Testing
- This is tested on real robot for both pi0 and pi05 policy

fix(async): Add pre and post processing to async inference and update docs
